// Everglen supplemental asset runtime.
// Reconstructs the compact staged atlas and renders assets through EVERGLEN_RENDER.
(() => {
  const state=window.SIM_STATE,art=window.EVERGLEN_2D_ART,registry=window.EVERGLEN_RENDER;if(!state||!art?.canvas||!registry)return;
  const root='assets/everglen/',ctx=art.canvas.getContext('2d');ctx.imageSmoothingEnabled=false;
  const status={ready:false,available:false,error:null,used:{},draws:0,totalAssets:0};let catalog={atlas:{},sources:{}},image=null;
  const decode=s=>Uint8Array.from(atob(s.trim()),c=>c.charCodeAt(0));
  const read=async path=>{try{const r=await fetch(root+path);if(r.ok)return r.text();}catch(_){}return await new Promise((resolve,reject)=>{const x=new XMLHttpRequest();x.open('GET',root+path,true);x.onload=()=>x.status===0||x.status===200?resolve(x.responseText):reject(new Error(`HTTP ${x.status} for ${path}`));x.onerror=()=>reject(new Error(`XHR failed for ${path}`));x.send();})};
  const gunzip=async bytes=>{if(!window.DecompressionStream)throw new Error('DecompressionStream unavailable');const ds=new DecompressionStream('gzip'),stream=new Blob([bytes]).stream().pipeThrough(ds);return JSON.parse(await new Response(stream).text())};
  async function load(){try{const[mt,at]=await Promise.all([read('supplemental_asset_manifest.json.gz.b64'),read('supplemental_asset_atlas.b64')]);catalog=await gunzip(decode(mt));image=await createImageBitmap(new Blob([decode(at)],{type:'image/webp'}));status.totalAssets=Object.keys(catalog.atlas||{}).length;status.available=true}catch(e){status.error=String(e?.message||e);console.error('Everglen supplemental asset load failed:',status.error)}finally{status.ready=true;window.EVERGLEN_SUPPLEMENTAL_ASSETS={status,catalog}}}
  const hash=(x,y,s=17)=>{const v=Math.sin(x*12.9898+y*78.233+s*37.719)*43758.5453;return v-Math.floor(v)};
  const entries=p=>Object.entries(catalog.atlas||{}).filter(([k])=>k.startsWith(p));
  const pick=(a,s)=>a.length?a[Math.abs(Math.floor(s))%a.length]:null;
  const draw=(k,x,y,w,h)=>{const r=catalog.atlas?.[k];if(!r||!image)return false;ctx.drawImage(image,r.x,r.y,r.w,r.h,x,y,w,h);status.used[k]=(status.used[k]||0)+1;status.draws++;return true};
  const frame=(k,i,x,y,w,h)=>{const r=catalog.atlas?.[k];if(!r||!image)return false;const n=r.frames||1,fw=r.w/n,fi=((i%n)+n)%n;ctx.drawImage(image,r.x+fw*fi,r.y,fw,r.h,x,y,w,h);status.used[k]=(status.used[k]||0)+1;status.draws++;return true};
  const pos=(x,y,t)=>[t.cx+x*t.z/8,t.cy+y*t.z/8];
  function overworld(t){const terrain=entries('overworld:ow_terrain_base_'),nature=entries('overworld:ow_props_nature_');for(let sy=0;sy<180;sy+=8)for(let sx=0;sx<320;sx+=8){const wx=(sx-t.cx)*8/t.z,wy=(sy-t.cy)*8/t.z;if(terrain.length&&hash(Math.floor(wx/8),Math.floor(wy/8),53)>.88){const h=pick(terrain,hash(wx,wy,51)*terrain.length);if(h)draw(h[0],sx,sy,8,8)}}if(nature.length)for(let x=-1100;x<1100;x+=72)for(let y=-720;y<720;y+=72){if(hash(x/72,y/72,61)<.72)continue;const[sx,sy]=pos(x,y,t);if(sx>-12&&sx<332&&sy>-12&&sy<192){const h=pick(nature,hash(x,y,62)*nature.length);if(h)draw(h[0],sx-4,sy-7,8,8)}}}
  function rocks(t){const all=entries('rocks:rockpack_');if(!all.length)return;(state.resources||[]).forEach((r,i)=>{if(r?.depleted||typeof r.x!=='number'||typeof r.y!=='number')return;const[sx,sy]=pos(r.x,r.y,t);if(sx>-12&&sx<332&&sy>-12&&sy<192){const h=pick(all,i+Math.floor(state.tick/90));if(h)draw(h[0],sx-6,sy-6,12,12)}})}
  const oreMap={coal:'ore_coal',iron:'ore_iron_ore',gold:'ore_gold_ore',copper:'ore_copper_ore',diamond:'ore_diamond',emerald:'ore_emerald',lapis:'ore_lapis',redstone:'ore_redstone'};
  function ores(t){const all=entries('mystic_ores:ore_');if(!all.length)return;(state.resources||[]).forEach((r,i)=>{if(r?.depleted||typeof r.x!=='number'||typeof r.y!=='number')return;const type=String(r.type||r.resource||r.kind||'').toLowerCase(),mapped=oreMap[type],key=mapped&&catalog.atlas?.['mystic_ores:'+mapped]?'mystic_ores:'+mapped:pick(all,i)?.[0];const[sx,sy]=pos(r.x,r.y,t);if(key&&sx>-10&&sx<330&&sy>-10&&sy<190)draw(key,sx+4,sy-7,7,7)})}
  function props(t){const groups=['mega_props:mp_Tiles_VillageProps_','mega_props:mp_Tiles_VillageFixtures_','mega_props:mp_Tiles_Market_','mega_props:mp_Tiles_Blacksmith_','mega_props:mp_Tiles_Tavern_','mega_props:mp_Tiles_Architecture_','mega_props:mp_Tiles_Adventure_','mega_props:mp_Tiles_Nature_'];(state.settlements||[]).forEach((s,si)=>{const pop=(state.npcs||[]).filter(n=>n.alive&&n.settlementId===s.id).length,all=entries(groups[si%groups.length]);if(!all.length)return;const count=Math.min(6,2+Math.floor(pop/12));for(let i=0;i<count;i++){const h=pick(all,si*17+i+Math.floor(state.tick/180)),[sx,sy]=pos(s.x-18+(i%3)*18,s.y+14+Math.floor(i/3)*12,t);if(h&&sx>-15&&sx<335&&sy>-15&&sy<195)draw(h[0],sx-5,sy-6,10,10)}})}
  function kingdom(t){const sets=['acker','duneveil','frosthold','knochen','korallen','lichtung','pilze','pilzfeld'];sets.forEach((set,si)=>{const all=entries('kingdom:king_'+set+'_'),s=state.settlements?.[si];if(!all.length||!s)return;for(let i=0;i<2;i++){const[sx,sy]=pos(s.x+(i?12:-12),s.y-10,t),h=pick(all,Math.floor(state.tick/120)+i*7);if(h&&sx>-15&&sx<335&&sy>-15&&sy<195)draw(h[0],sx-5,sy-5,10,10)}})}
  function vessels(t){const all=entries('vessels:vessel_');if(!all.length)return;for(let i=0;i<3;i++){const x=-650+i*420+Math.sin((state.tick+i*41)/40)*80,y=80+Math.sin(x/170)*100,[sx,sy]=pos(x,y,t),h=pick(all,i+Math.floor(state.tick/30));if(h&&sx>-20&&sx<340&&sy>-20&&sy<200)frame(h[0],Math.floor(state.tick/12),sx-8,sy-5,16,9)}}
  function military(t){const all=entries('knights:knight_'),equip=entries('roguey:equip_');if(!all.length)return;const roles=new Set(['militia','soldier','archer','spearman','cavalry','knight','paladin','captain','general','marshal']);(state.npcs||[]).forEach((n,i)=>{if(!n.alive||!roles.has(n.roleId))return;const[sx,sy]=pos(n.x,n.y,t);if(sx<-15||sx>335||sy<-20||sy>200)return;const action=n.aiDecision?.action,token=action==='confront'?'attack_1':action==='train'?'defend':'walk',cand=all.filter(([k])=>k.includes('_'+token)),h=pick(cand.length?cand:all,i+Math.floor(state.tick/5));if(h)frame(h[0],Math.floor(state.tick/5),sx-7,sy-14,14,14);const e=pick(equip,i+Math.floor(state.tick/90));if(e){const r=catalog.atlas[e[0]],cols=r.cols||16,rows=r.rows||16,cell=r.w/cols,slot=Math.abs(i+Math.floor(state.tick/90))%(cols*rows),col=slot%cols,row=Math.floor(slot/cols);ctx.drawImage(image,r.x+col*cell,r.y+row*cell,cell,cell,sx+5,sy-8,4,4);status.used[e[0]]=(status.used[e[0]]||0)+1;status.draws++}})}
  function render(){if(!status.available||!image)return;const z=state.camera?.zoom||1,t={z,cx:160-(state.camera?.x||0)*z/8,cy:90-(state.camera?.y||0)*z/8};overworld(t);rocks(t);ores(t);kingdom(t);props(t);vessels(t);military(t)}
  registry.register({name:'supplemental-assets',priority:275,draw:render});
  window.EVERGLEN_SUPPLEMENTAL_ASSETS={status,catalog};load();
})();
