// Everglen Roguey Arms & Armor equipment stage.
// Equipment is layered after the animated Pixel Crawler body; it never paints a second NPC body.
(() => {
  const state=window.SIM_STATE,art=window.EVERGLEN_2D_ART,registry=window.EVERGLEN_RENDER;
  if(!state||!art?.canvas||!registry)return;
  const ctx=art.canvas.getContext('2d'),root='assets/everglen/';
  let catalog=null,image=null,ready=false;
  const decode=s=>{let v=String(s).trim().replace(/^data:[^,]+,/,'').replace(/[^A-Za-z0-9+/_=-]/g,'').replace(/-/g,'+').replace(/_/g,'/');v=v.padEnd(v.length+((4-v.length%4)%4),'=');return Uint8Array.from(atob(v),c=>c.charCodeAt(0));};
  const load=async()=>{try{const[m,a]=await Promise.all([fetch(root+'supplemental_asset_manifest.json.gz.b64').then(r=>r.text()),fetch(root+'supplemental_asset_atlas.b64').then(r=>r.text())]);if(!window.DecompressionStream)throw new Error('DecompressionStream unavailable');const ds=new DecompressionStream('gzip');catalog=JSON.parse(await new Response(new Blob([decode(m)]).stream().pipeThrough(ds)).text());image=await createImageBitmap(new Blob([decode(a)],{type:'image/webp'}));ready=true;window.EVERGLEN_EQUIPMENT={ready:true,catalog};}catch(e){window.EVERGLEN_EQUIPMENT={ready:false,error:String(e?.message||e)};console.warn('Everglen equipment load failed:',e);}};
  const roleClass=n=>{const r=String(n.roleId||n.professionId||'').toLowerCase();if(['archer','ranger'].includes(r))return'archer';if(['cavalry','knight','paladin'].includes(r))return'heavy';if(['general','marshal','captain','commander'].includes(r))return'leader';return'melee';};
  const hash=(v,s=0)=>{let h=2166136261>>>0,x=`${v}|${s}`;for(let i=0;i<x.length;i++){h^=x.charCodeAt(i);h=Math.imul(h,16777619);}return(h>>>0)/4294967296;};
  const draw=()=>{if(!ready||!catalog||!image)return;const entries=Object.entries(catalog.atlas||{}).filter(([k])=>k.startsWith('roguey:equip_'));if(!entries.length)return;const military=new Set(['militia','soldier','archer','spearman','cavalry','knight','paladin','captain','general','marshal','berserker','bodyguard','guard','warrior','fighter','mercenary','raider','ranger']);const z=state.camera?.zoom||1,cx=160-(state.camera?.x||0)*z/8,cy=90-(state.camera?.y||0)*z/8;ctx.save();ctx.translate(cx,cy);ctx.scale(z/8,z/8);ctx.imageSmoothingEnabled=false;(state.npcs||[]).forEach((n,i)=>{const role=String(n.roleId||'').toLowerCase();if(!n.alive||!military.has(role))return;const roleSeed={archer:1,heavy:2,leader:3,melee:4}[roleClass(n)]||4,entry=entries[Math.floor(hash(n.id||i,roleSeed)*entries.length)],r=entry[1];const cols=Number(r.cols)||16,rows=Number(r.rows)||16,cell=Math.min(r.w/cols,r.h/rows),slot=Math.floor(hash(n.id||i,roleSeed+17)*(cols*rows)),sx=r.x+(slot%cols)*cell,sy=r.y+Math.floor(slot/cols)*cell;const size=6*(n.visual?.bodyScale||1),offset=roleClass(n)==='archer'?4:3;ctx.drawImage(image,sx,sy,cell,cell,Math.round(n.x+offset),Math.round(n.y-size*1.45),Math.round(size),Math.round(size));});ctx.restore();};
  registry.register({name:'everglen-equipment',priority:287,draw});
  load();
})();
