// Emergent family, clan and inheritance system.
// Phase 2 family layer: bloodlines, kinship, reputation, wealth, inheritance and generational conflict.
(() => {
  const state=window.SIM_STATE;if(!state)return;
  const P=window.NPC_PERSONALITY,R=window.NPC_RELATIONSHIPS,M=window.NPC_MEMORY,ROLE=window.ROLE_BY_ID||{};
  const NAMES=['Alder','Ashford','Blackwood','Bright','Cedar','Crowe','Dawn','Ember','Frost','Hawthorne','Ironheart','Kingsley','Moon','Oak','Raven','Rivera','Stone','Thorne','Vale','Wren'];
  const ADULT=18,MAX_CHILDREN=6,clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,v));
  const alive=()=>state.npcs.filter(n=>n.alive),find=id=>state.npcs.find(n=>n.id===id)||null,score=(n,k)=>P?.score(n,k)??50;
  function ensure(n){n.parents=Array.isArray(n.parents)?n.parents:(Array.isArray(n.parentIds)?n.parentIds.slice():[]);n.parentIds=n.parents.slice();n.childrenIds=Array.isArray(n.childrenIds)?n.childrenIds:[];n.spouseId=n.spouseId??n.partnerId??null;n.partnerId=n.spouseId;n.familyGeneration=n.familyGeneration??1;n.familyReputation=n.familyReputation??50;n.estate=n.estate||{gold:Math.max(0,n.wealth||0),land:0,buildings:0,titles:[]};n.legitimacy=n.legitimacy??clamp(45+score(n,'loyalty')*.25+score(n,'ambition')*.15);return n;}
  const family=n=>n?.familyId?state.families.find(f=>f.id===n.familyId):null;
  function createFamily(seed){const id=`family-${seed.id}`;let old=state.families.find(f=>f.id===id);if(old)return old;const f={id,name:NAMES[(state.families.length+Math.abs(Number(seed.id)||0))%NAMES.length],founderId:seed.id,members:[seed.id],wealth:seed.wealth||0,influence:5,reputation:seed.reputation||50,prestige:10,generation:1,seat:seed.home||seed.settlementId||null,clanId:null,history:[],rivalries:[],traditions:[],successionDisputes:0};state.families.push(f);seed.familyId=f.id;seed.familyName=f.name;return f;}
  function initialize(){const map=new Map(state.families.map(f=>[f.id,f]));alive().forEach(n=>{ensure(n);let f=n.familyId?map.get(n.familyId):null;if(!f)f=createFamily(n);f.members=f.members||[];if(!f.members.includes(n.id))f.members.push(n.id);n.familyName=f.name;n.familyGeneration=n.familyGeneration||f.generation||1;});rebuild();state._familiesReady=true;}
  function rebuild(){state.families.forEach(f=>{f.members=f.members||[];const members=alive().filter(n=>n.familyId===f.id);f.members=members.map(n=>n.id);f.wealth=members.reduce((x,n)=>x+(n.wealth||0),0);f.influence=members.reduce((x,n)=>x+(n.influence||0)+(n.legitimacy||0)*.08,0);f.reputation=members.length?members.reduce((x,n)=>x+(n.reputation||50),0)/members.length:f.reputation||50;f.prestige=(f.prestige||10)*.995+members.reduce((x,n)=>x+(n.roleId==='king'||n.roleId==='emperor'?18:n.roleId==='duke'?8:n.roleId==='count'?4:0),0)*.02;});}
  function kin(a,b){if(!a||!b)return 0;if(a.id===b.id)return 100;const ap=new Set(a.parents||[]),bp=new Set(b.parents||[]);if(ap.has(b.id)||bp.has(a.id)||(a.childrenIds||[]).includes(b.id)||(b.childrenIds||[]).includes(a.id))return 95;if([...ap].some(x=>bp.has(x)))return 82;if(a.familyId&&a.familyId===b.familyId)return 68;return 0;}
  function marriageScore(a,b){if(!a||!b)return -999;if(a.familyId&&a.familyId===b.familyId)return -999;const comp=R?.compatibility?.(a,b)??0,ta=R?.trustValue?.(a,b.id)??50,tb=R?.trustValue?.(b,a.id)??50,social=(score(a,'sociability')+score(b,'sociability'))*.08,kind=(score(a,'kindness')+score(b,'kindness'))*.07,loyal=(score(a,'loyalty')+score(b,'loyalty'))*.07,faction=a.faction&&a.faction===b.faction?8:-4,ageGap=Math.abs(a.age-b.age),age=ageGap<=6?9:ageGap<=12?3:-8,wealth=clamp(((a.wealth||0)+(b.wealth||0))/80,0,12),amb=Math.max(0,Math.abs(score(a,'ambition')-score(b,'ambition'))-40)*.2;return comp*.72+(ta+tb)*.22+social+kind+loyal+faction+age+wealth-amb;}
  function marry(a,b){ensure(a);ensure(b);if(!a||!b||a.id===b.id||!a.alive||!b.alive||a.spouseId||b.spouseId||a.age<ADULT||b.age<ADULT||Math.abs(a.age-b.age)>22)return false;const s=marriageScore(a,b);if(s<62)return false;a.spouseId=b.id;b.spouseId=a.id;a.partnerId=b.id;b.partnerId=a.id;a.estate.gold=(a.estate.gold||0)+(b.estate.gold||0)*.15;b.estate.gold=(b.estate.gold||0)+(a.estate.gold||0)*.08;a.mood=clamp((a.mood||65)+8);b.mood=clamp((b.mood||65)+8);R?.interact?.(a,b,'help',2);M?.experience?.(a,`${b.name} became my spouse.`,'marriage',4,b.id,'joy',-10,true);M?.experience?.(b,`${a.name} became my spouse.`,'marriage',4,a.id,'joy',-10,true);const fa=family(a),fb=family(b);if(fa&&fb&&fa.id!==fb.id){fa.reputation=clamp((fa.reputation||50)+1);fb.reputation=clamp((fb.reputation||50)+1);}return true;}
  function inherit(d){if(!d||d.alive||d._inheritanceSettled)return;ensure(d);d._inheritanceSettled=true;const kids=(d.childrenIds||[]).map(find).filter(n=>n?.alive),spouse=d.spouseId?find(d.spouseId):null;const rank=n=>(n.roleId==='heir'?1000:0)+(n.legitimacy||0)+(n.age>=ADULT?40:0)+score(n,'loyalty')*.2+score(n,'ambition')*.1;const ordered=kids.slice().sort((a,b)=>rank(b)-rank(a)||b.age-a.age),heir=ordered[0]||spouse;if(!heir)return;ensure(heir);const estate=d.estate||{gold:d.wealth||0,land:0,buildings:0,titles:[]},gold=estate.gold||d.wealth||0;heir.wealth=(heir.wealth||0)+gold;heir.estate.gold=(heir.estate.gold||0)+gold;heir.estate.land=(heir.estate.land||0)+(estate.land||0);heir.estate.buildings=(heir.estate.buildings||0)+(estate.buildings||0);heir.estate.titles=[...new Set([...(heir.estate.titles||[]),...(estate.titles||[])])];heir.legitimacy=clamp((heir.legitimacy||50)+12);if(['king','queen','duke','count','baron','prince','emperor','empress','governor','mayor','chancellor'].includes(d.roleId)){heir.roleId=d.roleId;heir.roleName=ROLE[heir.roleId]?.name||d.roleName||d.roleId;}const f=family(d);if(f){f.successionDisputes=f.successionDisputes||0;f.history=(f.history||[]).concat(`Year ${state.year}: ${d.name} died; ${heir.name} inherited.`).slice(-20);f.reputation=clamp((f.reputation||50)+2);}M?.experience?.(heir,`Inherited the estate of ${d.name}.`,'inheritance',4,d.id,'pride',-8,true);if(d.roleId)M?.experience?.(heir,`Inherited the title of ${d.roleName||d.roleId}.`,'succession',4,d.id,'pride',-10,true);ordered.slice(1).forEach(r=>{if(f){f.successionDisputes++;r.grievance=(r.grievance||0)+8-score(r,'loyalty')*.03;M?.experience?.(r,`${heir.name} inherited what I believed should be mine.`,'succession_conflict',4,heir.id,'anger',-6,true);}});}
  function onBirth(child,parents){parents=(parents||[]).filter(Boolean);parents.forEach(ensure);ensure(child);const a=parents[0],b=parents[1],f=family(a)||family(b)||createFamily(a||b||child);child.familyId=f.id;child.familyName=f.name;child.parents=parents.map(p=>p.id);child.parentIds=child.parents.slice();child.familyGeneration=Math.max(...parents.map(p=>p.familyGeneration||family(p)?.generation||1))+1;child.childrenIds=[];child.spouseId=null;child.partnerId=null;child.estate={gold:0,land:0,buildings:0,titles:[]};child.legitimacy=clamp(40+(score(a||child,'loyalty')+score(b||child,'loyalty'))*.12);parents.forEach(p=>{p.childrenIds=p.childrenIds||[];if(!p.childrenIds.includes(child.id))p.childrenIds.push(child.id);M?.experience?.(p,`${child.name} was born into my family.`,'birth',4,child.id,'joy',-8,true);});f.members=f.members||[];if(!f.members.includes(child.id))f.members.push(child.id);f.generation=Math.max(f.generation||1,child.familyGeneration);f.history=(f.history||[]).concat(`Year ${state.year}: ${child.name} joined generation ${child.familyGeneration}.`).slice(-20);}
  function maybeBirth(a,b){if(!a||!b||!a.alive||!b.alive||a.spouseId!==b.id||a.age<18||b.age<18||a.age>48||b.age>55)return false;const count=(a.childrenIds||[]).map(find).filter(n=>n?.alive&&n.age<18).length;if(count>=MAX_CHILDREN)return false;const trust=((R?.trustValue?.(a,b.id)??50)+(R?.trustValue?.(b,a.id)??50))/2,desire=40+trust*.25+((a.needs?.belonging||50)+(b.needs?.belonging||50))*.08+(score(a,'kindness')+score(b,'kindness'))*.08-count*9;if(Math.random()>clamp(desire/190,.025,.28))return false;const id=state.npcs.reduce((m,n)=>Math.max(m,Number(n.id)||0),0)+1,child=window.SIM_API?.createNpc?.(id-1,a.faction)||{id,name:`Child ${id}`,age:0,sex:'F',alive:true,trait:'calm',wealth:0,mood:70,health:100,hunger:10,energy:90,memories:[],relations:[],childrenIds:[],parentIds:[],familyId:null,faction:a.faction,x:(a.x+b.x)/2,y:(a.y+b.y)/2};child.age=0;child.sex=Math.random()>.5?'F':'M';child.faction=a.faction;child.x=(a.x+b.x)/2;child.y=(a.y+b.y)/2;child.alive=true;child.lastAction='Born into a family';state.npcs.push(child);onBirth(child,[a,b]);window.SIM_API?.log?.(`${a.name} and ${b.name} welcomed ${child.name}.`);return true;}
  function step(){if(!state._familiesReady)initialize();const adults=alive().filter(n=>{ensure(n);return n.age>=ADULT;});if(state.tick%18===0)adults.forEach(n=>{if(n.spouseId||n.age>68)return;const opts=alive().filter(x=>x.id!==n.id&&!x.spouseId&&x.sex!==n.sex&&x.age>=ADULT&&Math.abs(x.age-n.age)<=14&&x.faction===n.faction).map(x=>({n:x,s:marriageScore(n,x)})).sort((a,b)=>b.s-a.s);if(opts[0]&&opts[0].s+score(n,'sociability')*.12+(n.needs?.belonging||0)*.18>84&&Math.random()<.18)marry(n,opts[0].n);});if(state.tick%30===0)adults.filter(n=>n.spouseId).forEach(a=>{const b=find(a.spouseId);if(b&&a.id<b.id)maybeBirth(a,b);});if(state.tick%12===0){state.npcs.filter(n=>!n.alive&&!n._inheritanceSettled).forEach(inherit);rebuild();}adults.forEach(n=>{const f=family(n);if(!f)return;n.familyReputation=clamp(f.reputation||50);n.familyLegacy=(f.prestige||10)+Math.max(0,(f.members||[]).length-1)*.5;const parents=(n.parents||[]).map(find).filter(Boolean);if(parents.length){const inherited=(parents.reduce((s,p)=>s+(p.legitimacy||50),0)/parents.length);n.legitimacy=clamp((n.legitimacy||50)*.97+inherited*.03);}});}
  window.NPC_FAMILIES={initialize,rebuild,kin,marriageScore,marry,inherit,onBirth,maybeBirth,step};
  if(state.registerSystem)state.registerSystem({name:'families',step,priority:50});
})();
