// Integrates the existing family, NPC economy and Phase 5 property systems.
(() => {
  const state=window.SIM_STATE;if(!state)return;
  const finite=(v,fallback=0)=>Number.isFinite(Number(v))?Number(v):fallback;
  const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,finite(v,a)));
  const alive=()=>state.npcs.filter(n=>n.alive);
  const members=f=>alive().filter(n=>n.familyId===f.id);
  const property=()=>window.EVERGLEN_PROPERTY;
  const score=(n,k)=>window.NPC_PERSONALITY?.score?.(n,k)??50;
  function ensureFamily(f){
    f.wealth=finite(f.wealth);f.legacy=finite(f.legacy);f.land=finite(f.land);f.businesses=finite(f.businesses);
    f.households=finite(f.households);f.income=finite(f.income);f.expenses=finite(f.expenses);f.economicPower=finite(f.economicPower);
    f.prestige=finite(f.prestige,50);f.netWorth=finite(f.netWorth);f.familyCashflow=finite(f.familyCashflow);
    f.assets=f.assets&&typeof f.assets==='object'?f.assets:{propertyValue:0,land:0,buildings:0};f.heirs=Array.isArray(f.heirs)?f.heirs:[];
  }
  function ensureNpc(n){n.householdId=n.householdId||null;n.householdRole=n.householdRole||null;n.familyContribution=finite(n.familyContribution);n.familySupport=finite(n.familySupport);}
  function householdResponsibility(n){return (score(n,'discipline')+score(n,'loyalty')+score(n,'kindness'))/3;}
  function chooseHouseholdHead(ms){return ms.filter(n=>n.age>=18).sort((a,b)=>{const va=(a.spouseId?12:0)+(a.roleId==='heir'?18:0)+(a.influence||0)*2+(a.wealth||0)*.08+householdResponsibility(a)*.35;const vb=(b.spouseId?12:0)+(b.roleId==='heir'?18:0)+(b.influence||0)*2+(b.wealth||0)*.08+householdResponsibility(b)*.35;return vb-va;})[0]||ms[0]||null;}
  function householdKey(n){return n.spouseId&&n.id<n.spouseId?`household-${n.id}-${n.spouseId}`:n.spouseId?`household-${n.spouseId}-${n.id}`:`family-${n.familyId}-member-${n.id}`;}
  function rebuildHouseholds(f,ms){const heads=new Map();ms.forEach(n=>{ensureNpc(n);let head=n.spouseId?ms.find(x=>x.id===n.spouseId)||n:n;head=chooseHouseholdHead([head,n])||n;const key=n.spouseId&&ms.some(x=>x.id===n.spouseId)?householdKey(n):`family-${f.id}-member-${n.id}`;if(!heads.has(key))heads.set(key,head.id);n.householdId=key;n.householdRole=n.id===head.id?'head':(n.age<18?'child':n.spouseId?'spouse':'member');});f.households=heads.size;f.householdIds=[...heads.keys()];}
  function propertySnapshot(f,ms){let value=0,land=0,buildings=0,businesses=0;ms.forEach(n=>{const assets=n.property?.assets||[];if(!assets.length)return;const s=state.settlements.find(x=>x.id===n.settlementId);const parcels=s?.property?.parcels||[];assets.forEach(id=>{const a=parcels.find(x=>x.id===id);if(!a)return;value+=finite(a.value);land+=['farm','estate','nobleEstate','mine'].includes(a.type)?1:0;buildings+=1;});businesses+=n.business?1:0;});f.assets={propertyValue:finite(Number(value.toFixed(2))),land,buildings};f.land=land;f.businesses=businesses;f.propertyValue=f.assets.propertyValue;return f.assets;}
  function familyLedger(f,ms){let income=0,expenses=0;ms.forEach(n=>{income+=finite(n.wage)*.08+finite(n.lastOutputValue)*.012+finite(n.business?.revenue)*.03;expenses+=finite(n.needFoodCost)*.08+finite(n.debt)*.004;});f.income=finite(income);f.expenses=finite(expenses);f.familyCashflow=finite(income-expenses);const cash=ms.reduce((s,n)=>s+finite(n.wealth),0),assets=finite(f.assets?.propertyValue);const debt=ms.reduce((s,n)=>s+finite(n.debt),0);f.wealth=finite(Number(cash.toFixed(2)));f.netWorth=finite(Number((cash+assets-debt).toFixed(2)));f.economicPower=clamp(f.netWorth*.055+f.businesses*5+f.land*2.5+f.prestige*.35);f.legacy=finite(Number((f.legacy*.992+f.netWorth*.004+f.prestige*.05).toFixed(2)));}
  function familySupport(f,ms){if(!ms.length)return;const adults=ms.filter(n=>n.age>=18),children=ms.filter(n=>n.age<18),poor=adults.filter(n=>finite(n.wealth)<8);const pool=Math.min(adults.reduce((s,n)=>s+Math.max(0,finite(n.wealth)-18)*.012,0),poor.length*2.5);if(pool>0&&poor.length)poor.forEach(n=>{const grant=Math.min(2.5,pool/poor.length);n.wealth=finite(n.wealth)+grant;n.familySupport=finite(n.familySupport)+grant;});f.dependents=children.length;f.adults=adults.length;f.poorMembers=poor.length;f.familyBurden=adults.length?clamp((children.length*7+poor.length*5)/adults.length):0;}
  function professionLegacy(f,ms){const counts={};ms.forEach(n=>{if(n.age>=18&&n.roleId&&n.roleId!=='citizen')counts[n.roleId]=(counts[n.roleId]||0)+1;});f.professions=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,6).map(([id,count])=>({id,count}));const dominant=f.professions[0];f.traditionProfession=dominant?.id||null;ms.forEach(n=>{if(n.age<18&&dominant&&Math.random()<.02)n.familyProfessionInfluence=dominant.id;});}
  function syncEstate(f,ms){const estate=f.estate=f.estate||{gold:0,land:0,buildings:0,titles:[]};estate.gold=finite(Number(ms.reduce((s,n)=>s+finite(n.estate?.gold),0).toFixed(2)));estate.land=finite(f.assets?.land);estate.buildings=finite(f.assets?.buildings);estate.familyNetWorth=finite(f.netWorth);estate.economicPower=finite(f.economicPower);}
  function successionPreview(f,ms){const adults=ms.filter(n=>n.age>=18).sort((a,b)=>{const va=(a.roleId==='heir'?100:0)+(a.legitimacy||50)+score(a,'loyalty')*.25+score(a,'ambition')*.12+(a.influence||0)*2;const vb=(b.roleId==='heir'?100:0)+(b.legitimacy||50)+score(b,'loyalty')*.25+score(b,'ambition')*.12+(b.influence||0)*2;return vb-va;});f.heirs=adults.slice(0,3).map((n,i)=>({id:n.id,name:n.name,rank:i+1,share:i===0?.6:i===1?.25:.15}));f.primaryHeirId=f.heirs[0]?.id||null;}
  function deathBridge(){if(!property()?.inheritance)return;state.npcs.filter(n=>!n.alive&&!n._propertyInheritanceSettled).forEach(n=>{const s=state.settlements.find(x=>x.id===n.settlementId);if(!s)return;property().inheritance(n,s);n._propertyInheritanceSettled=true;});}
  function step(){if(!state.running)return;if(state.tick%24===0)state.families.forEach(f=>{ensureFamily(f);const ms=members(f);if(!ms.length)return;rebuildHouseholds(f,ms);propertySnapshot(f,ms);familyLedger(f,ms);familySupport(f,ms);professionLegacy(f,ms);syncEstate(f,ms);successionPreview(f,ms);f.reputation=clamp(finite(f.reputation,50)*.998+f.economicPower*.002);ms.forEach(n=>{ensureNpc(n);n.familyContribution=clamp(finite(n.wage)*.08+finite(n.lastOutputValue)*.012+finite(n.business?.revenue)*.03,0,100);});});if(state.tick%60===0)deathBridge();}
  window.EVERGLEN_FAMILY_ECONOMY={step,propertySnapshot,familyLedger,rebuildHouseholds,successionPreview};
  if(state.registerSystem)state.registerSystem({name:'family-economy-integration',step,priority:76});
})();
