// Everglen God Mode: direct player interaction with the simulated world.
(() => {
  const state = window.SIM_STATE;
  if (!state) return;

  const TOOLS = [
    ['select','🖐 Select'],['move','✥ Move'],['bless','✨ Bless'],['smite','☠ Smite'],
    ['human','👤 Human'],['dwarf','⛏ Dwarf'],['elf','🧝 Elf'],['orc','👹 Orc'],['soldier','⚔ Soldier'],['king','👑 King'],
    ['gold','💰 Gold'],['iron','⛏ Iron'],['food','🌾 Food'],['wood','🌲 Wood'],['settlement','🏠 Settlement'],['meteor','☄ Meteor']
  ];
  let active=false,tool='select',moveTarget=null,busy=false;
  const uid=p=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;
  const rand=a=>a[Math.floor(Math.random()*a.length)];
  const applyEvent=(action,details={})=>{try{return window.EVERGLEN_PLAYER_EVENTS?.apply?.(action,{tool,...details})||null}catch(_){return null}};
  const note=text=>{state.feed=state.feed||[];state.feed.unshift(`Year ${state.year||1}, Day ${state.day||1}: ${text}`);state.feed=state.feed.slice(0,15);const feed=document.getElementById('eventFeed');if(feed)feed.innerHTML=state.feed.map(x=>`<li>${x}</li>`).join('')};
  const render=()=>{try{window.SIM_RENDER?.()}catch(_){}};
  const nearbyNpc=p=>(state.npcs||[]).filter(n=>n.alive).reduce((best,n)=>{const d=Math.hypot((n.x||0)-p.x,(n.y||0)-p.y);return !best||d<best.d?{n,d}:best},null);

  function setActive(value){active=!!value;state.godMode=active;updateUI();if(active)note('God Mode awakened. The world now responds directly to the player.')}
  function choose(next){tool=next;moveTarget=null;updateUI()}
  function updateUI(){const button=document.getElementById('godMode');if(button){button.textContent=active?'⚡ God Mode: ON':'☄ God Mode';button.classList.toggle('primary',active)}document.querySelectorAll('#godToolDock button[data-tool]').forEach(b=>b.classList.toggle('primary',b.dataset.tool===tool&&active));const label=document.getElementById('godToolLabel');if(label)label.textContent=active?`Tool: ${TOOLS.find(x=>x[0]===tool)?.[1]||tool}`:'God Mode off'}

  function ensureKingdom(){
    if(state.kingdoms?.length)return state.kingdoms[0];
    const k={id:uid('kingdom'),name:'Freefolk',color:'#79c2ff',capitalId:null,leaderId:null,treasury:100,power:25,stability:82,taxRate:.08,law:{crimePenalty:24,bribeBase:12},politics:{nobles:20,merchants:20,commons:50,clergy:10,army:0}};
    state.kingdoms=state.kingdoms||[];state.kingdoms.push(k);return k;
  }
  function summon(kind,p){
    const k=ensureKingdom(), ss=(state.settlements||[]).slice().sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y)), s=ss[0]||null;
    const role=kind==='soldier'?'soldier':kind==='king'?'king':'citizen';
    const age=kind==='king'?30+Math.floor(Math.random()*25):18+Math.floor(Math.random()*35);
    const traits=['brave','curious','ambitious','kind','greedy','loyal','clever','calm'];
    const n={id:uid('npc'),name:`${rand(['Ari','Bram','Cora','Dax','Elia','Faye','Gale','Hana','Ivo','Juno','Kian','Lena','Milo','Nia','Oren','Pia','Quill','Rhea','Sera','Tobin','Uma','Vale','Wren','Yara','Zane'])} ${Math.floor(Math.random()*90)+10}`,age,sex:Math.random()>.5?'F':'M',species:kind,trait:rand(traits),traits:[rand(traits)],roleId:role,roleName:role[0].toUpperCase()+role.slice(1),faction:k.id,settlementId:s?.id||null,x:p.x+(Math.random()-.5)*10,y:p.y+(Math.random()-.5)*10,target:null,speed:.45+Math.random()*.45,mood:70,health:100,hunger:10,energy:90,wealth:kind==='king'?300:20+Math.random()*80,goal:'Live and work',home:s?.name||null,parentIds:[],childrenIds:[],partnerId:null,relations:[],memories:[],alive:true,color:k.color,inventory:{food:2,wood:0,stone:0,iron:0,gold:kind==='king'?50:0,cloth:0,medicine:0,reagents:0,weapons:kind==='soldier'?1:0,armor:kind==='soldier'?1:0,tools:0},reputation:50,honor:kind==='king'?85:50,influence:kind==='king'?50:5,status:kind==='king'?90:1,classTier:kind==='king'?'royal':'peasant',education:kind==='king'?70:0,ambition:50,loyalty:60,crimeHeat:0,arrests:0,crimes:0,term:0,lastAction:'Summoned by the player',socialCooldown:0,grievance:0,fortune:50,visual:{species:kind,bodyScale:kind==='dwarf'?.72:kind==='giant'?1.35:.88}};
    state.npcs.push(n);if(s){s.homes=(s.homes||0)+1;s.wealth=(s.wealth||0)+2}if(kind==='king'){k.leaderId=n.id;k.capitalId=s?.id||k.capitalId}
    const intervention=applyEvent('summon',{x:p.x,y:p.y,target:{kind:'npc',id:n.id},details:`Summoned ${kind}`,entityId:n.id,entityIds:[n.id],created:true,consequences:[`Created 1 ${kind} NPC.`]});
    n.playerInterventionId=intervention?.id||null;note(`${kind} summoned at the chosen location.`);render();return true;
  }
  function resource(type,p){state.worldGen=state.worldGen||{resources:[],biomes:[],landmarks:[]};state.worldGen.resources=state.worldGen.resources||[];const r={id:uid('resource'),type,x:p.x,y:p.y,amount:100,depleted:false,playerPlaced:true};state.worldGen.resources.push(r);const intervention=applyEvent('create-resource',{x:p.x,y:p.y,target:{kind:'resource',type},details:`Created ${type} resource`,entityId:r.id,entityIds:[r.id],placed:true,consequences:[`Added 100 units of ${type} to the world.`]});r.playerInterventionId=intervention?.id||null;note(`A ${type} resource was created at the chosen location.`);render()}
  function settlement(p){const k=(state.kingdoms||[])[0]||null,s={id:uid('settlement'),name:`${rand(['Haven','Crossing','Hold','Watch','Village'])}`,type:'village',level:1,x:p.x,y:p.y,kingdomId:k?.id||null,founderId:null,rulerId:null,age:0,homes:6,buildings:3,stability:85,wealth:180,influence:3,resources:{food:80,wood:70,stone:45,iron:12,gold:15,cloth:5,medicine:4,reagents:3,weapons:2,armor:2,tools:8},history:[`Year ${state.year||1}: founded directly by the player.`],playerFounded:true};state.settlements=state.settlements||[];state.settlements.push(s);const intervention=applyEvent('found-settlement',{x:p.x,y:p.y,target:{kind:'settlement',name:s.name},details:`Founded ${s.name}`,entityId:s.id,entityIds:[s.id],founded:true,consequences:[`${s.name} entered the world as a player-founded settlement.`]});s.playerInterventionId=intervention?.id||null;note(`${s.name} was founded by divine intervention.`);render()}
  function meteor(p){state.meteorImpacts=state.meteorImpacts||[];const impact={x:p.x,y:p.y,life:80,playerCaused:true};state.meteorImpacts.push(impact);const kills=[],damaged=[];(state.npcs||[]).filter(n=>n.alive).forEach(n=>{const d=Math.hypot((n.x||0)-p.x,(n.y||0)-p.y);if(d<110)n.health=Math.max(0,(n.health||100)-Math.max(15,80-d*.45));if(n.health<=0){n.alive=false;kills.push(n.id)}});(state.settlements||[]).forEach(s=>{const d=Math.hypot((s.x||0)-p.x,(s.y||0)-p.y);if(d<150){s.stability=Math.max(0,(s.stability||0)-25);s.wealth=Math.max(0,(s.wealth||0)-30);s.history=s.history||[];s.history.push(`Year ${state.year||1}: struck by a player-summoned meteor.`);damaged.push(s.id)}});state.stability=Math.max(0,(state.stability||50)-5);applyEvent('meteor',{x:p.x,y:p.y,target:{kind:'world-point'},details:'Summoned meteor',memoryNpcIds:[...kills],memory:{type:'divine',text:'A player-summoned meteor brought destruction upon my world.',importance:96,permanent:true,emotion:'fear'},consequences:[`Killed ${kills.length} NPC${kills.length===1?'':'s'}.`,`Damaged ${damaged.length} settlement${damaged.length===1?'':'s'}.`],entityIds:[...kills,...damaged]});note('A meteor was summoned onto the world.');render();return true}
  function bless(p){const hit=nearbyNpc(p);if(!hit||hit.d>26/Math.max(.5,state.camera?.zoom||1))return false;const n=hit.n;n.health=100;n.mood=Math.min(100,(n.mood||50)+25);n.fortune=Math.min(100,(n.fortune||50)+20);n.grievance=Math.max(0,(n.grievance||0)-20);n.needState='stable';if(n.needs){n.needs.health=100;n.needs.safety=Math.min(100,(n.needs.safety||50)+20);n.needs.purpose=Math.min(100,(n.needs.purpose||50)+10)}applyEvent('bless',{x:n.x,y:n.y,target:{kind:'npc',id:n.id,name:n.name},details:'Restored health and improved mood, fortune and safety.',entityId:n.id,memoryNpcIds:[n.id],memory:{type:'divine',text:'A mysterious divine blessing restored and strengthened me.',importance:90,permanent:true,emotion:'joy'},consequences:['Health restored','Mood improved','Fortune improved','Grievance reduced']});note(`${n.name} was blessed by the player.`);render();return true}
  function smite(p){const hit=nearbyNpc(p);if(!hit||hit.d>26/Math.max(.5,state.camera?.zoom||1))return false;const n=hit.n;n.health=0;n.alive=false;applyEvent('smite',{x:n.x,y:n.y,target:{kind:'npc',id:n.id,name:n.name},details:'Killed NPC through direct divine intervention.',entityId:n.id,memoryNpcIds:[n.id],memory:{type:'divine',text:'I was struck down by a divine power.',importance:100,permanent:true,emotion:'fear'},consequences:[`${n.name} died.`]});note(`${n.name} was smitten.`);if(state.selected===n.id)state.selected=null;render();return true}
  function move(p){const hit=nearbyNpc(p);if(!moveTarget){if(!hit||hit.d>26/Math.max(.5,state.camera?.zoom||1))return false;moveTarget=hit.n;state.selected=hit.n.id;note(`Selected ${hit.n.name} for divine relocation.`);render();return true}const from={x:moveTarget.x,y:moveTarget.y};moveTarget.x=p.x;moveTarget.y=p.y;moveTarget.target={x:p.x,y:p.y};applyEvent('move',{x:p.x,y:p.y,target:{kind:'npc',id:moveTarget.id,name:moveTarget.name},details:`Relocated from (${Math.round(from.x)},${Math.round(from.y)}) to (${Math.round(p.x)},${Math.round(p.y)}).`,entityId:moveTarget.id,consequences:[`${moveTarget.name} was moved by the player.`]});note(`${moveTarget.name} was moved to a new location.`);moveTarget=null;render();return true}
  function handle(p,e){if(!active||busy||e.button!==0)return false;let handled=false;if(tool==='move')handled=move(p);else if(tool==='bless')handled=bless(p);else if(tool==='smite')handled=smite(p);else if(['human','dwarf','elf','orc','soldier','king'].includes(tool))handled=summon(tool,p);else if(['gold','iron','food','wood'].includes(tool)){resource(tool,p);handled=true}else if(tool==='settlement'){settlement(p);handled=true}else if(tool==='meteor')handled=meteor(p);return handled}
  function buildMenu(){if(document.getElementById('godToolDock'))return;const style=document.createElement('style');style.textContent=`#godToolDock{position:absolute;z-index:45;right:12px;bottom:86px;font-family:monospace;pointer-events:auto}#godToolPanel{display:none;width:250px;background:rgba(31,42,38,.98);border:2px solid #18231f;box-shadow:4px 4px #18231f;padding:8px}#godToolPanel.open{display:block}.god-title{font-size:10px;color:#e6c35d;margin-bottom:5px}.god-label{font-size:7px;color:#9eaaa0;margin-bottom:6px}.god-grid{display:grid;grid-template-columns:1fr 1fr;gap:4px}.god-grid button{font-size:8px;padding:6px 4px}.god-grid button.primary{outline:2px solid #e6c35d;background:#4b5a50}.god-help{font-size:7px;color:#9eaaa0;line-height:1.3;margin-top:7px}.god-toggle{font:inherit;font-weight:700;color:#f2f0dc;background:#3a4a43;border:2px solid #18231f;padding:8px 12px;box-shadow:3px 3px #18231f;cursor:pointer}`;document.head.appendChild(style);const dock=document.createElement('div');dock.id='godToolDock';dock.innerHTML=`<button class="god-toggle" id="godToolToggle">⚡ TOOLS</button><div id="godToolPanel"><div class="god-title">DIVINE TOOLBELT</div><div class="god-label" id="godToolLabel">God Mode off</div><div class="god-grid">${TOOLS.map(([id,label])=>`<button data-tool="${id}">${label}</button>`).join('')}</div><div class="god-help">Move: click an NPC, then click a destination. Other tools act directly on the clicked location.</div></div>`;document.body.appendChild(dock);document.getElementById('godToolToggle').addEventListener('click',()=>document.getElementById('godToolPanel').classList.toggle('open'));dock.querySelectorAll('[data-tool]').forEach(b=>b.addEventListener('click',()=>{setActive(true);choose(b.dataset.tool)}))}
  const godButton=document.getElementById('godMode');if(godButton)godButton.addEventListener('click',e=>{e.stopImmediatePropagation();setActive(!active)},true);
  if(window.EVERGLEN_INPUT?.register)window.EVERGLEN_INPUT.register({name:'god-mode',priority:10,events:['click'],hitTest:()=>active&&!busy,handle});
  buildMenu();
  window.EVERGLEN_GOD_MODE={activate:()=>setActive(true),deactivate:()=>setActive(false),choose,tools:TOOLS,meteorAt:meteor,get active(){return active},get tool(){return tool}};
  updateUI();
})();
