// Everglen NPC identity visuals.
// Final visual pass: use the supplied race/profession pixel assets as the canonical civilian silhouette.
// Simulation state remains authoritative and this stage is render-only.
(() => {
  const state=window.SIM_STATE, registry=window.EVERGLEN_RENDER;
  if(!state||!registry)return;
  const canvas=document.getElementById('worldCanvas');
  const hash=(value,salt=0)=>{let h=2166136261>>>0;const text=`${value}|${salt}`;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619);}return(h>>>0)/4294967296;};
  const militaryRoles=new Set(['militia','soldier','archer','spearman','cavalry','knight','paladin','captain','general','marshal','berserker','bodyguard']);
  const professionVisual={farmer:'farmer',miner:'blacksmith',woodcutter:'woodcutter',builder:'blacksmith',blacksmith:'blacksmith',armorer:'blacksmith',carpenter:'woodcutter',weaver:'farmer',baker:'farmer',cook:'farmer',healer:'apothecary',doctor:'apothecary',merchant:'banker',trader:'banker',shipwright:'woodcutter',sailor:'farmer',scholar:'apothecary',teacher:'apothecary',engineer:'blacksmith',architect:'blacksmith',hunter:'woodcutter',forager:'farmer',fisher:'farmer',thief:'banker',burglar:'banker',bandit:'blacksmith',smuggler:'banker',spy:'banker',cleric:'apothecary',druid:'apothecary',mage:'apothecary',wizard:'apothecary',alchemist:'apothecary',enchanter:'apothecary',mason:'blacksmith',herbalist:'apothecary',peddler:'banker',innkeeper:'farmer',shopkeeper:'banker',beastmaster:'woodcutter',farrier:'blacksmith',artist:'farmer',musician:'farmer',courier:'farmer',scribe:'apothecary',lawkeeper:'blacksmith',tax_collector:'banker',judge:'banker',librarian:'apothecary',furniture_maker:'woodcutter'};
  const ageScale=n=>window.EVERGLEN_AGE_VISUALS?.visualScale?.(window.EVERGLEN_AGE_VISUALS.ageBand?.(n.age))||1;
  const bodyProfile=n=>{const g=String(n.gender??n.sex??'').toLowerCase(),female=g==='f'||g==='female'||g==='woman';return{gender:female?'female':'male',width:(.94+hash(n.id||`${n.x}:${n.y}`,72)*.12)*(female?.97:1.02)};};
  const group=role=>{if(['farmer','rancher','forager','fisher','hunter','beastmaster'].includes(role))return'field';if(['miner','woodcutter','builder','mason','blacksmith','carpenter','engineer','architect','shipwright','farrier','furniture_maker'].includes(role))return'craft';if(['merchant','trader','peddler','shopkeeper','innkeeper','banker'].includes(role))return'trade';if(['healer','doctor','herbalist','alchemist','cleric','priest','druid','scholar','teacher','scribe','librarian'].includes(role))return'care';if(militaryRoles.has(role))return'military';return'general';};
  function drawAsset(ctx,n,sx,sy){const assets=window.EVERGLEN_ASSETS;if(!assets?.ready||!assets.images?.raceProf)return false;const race=n.raceId,visual=professionVisual[n.roleId]||professionVisual[n.professionId]||'farmer',r=assets.manifest?.raceProf?.[race]?.[visual];if(!r)return false;const base=militaryRoles.has(n.roleId)?14:12,scale=(n.visual?.bodyScale||1)*ageScale(n),dh=base*1.08*scale,aspect=r.w/Math.max(1,r.h),profile=bodyProfile(n),dw=Math.max(4,dh*aspect*.88*profile.width);ctx.save();ctx.imageSmoothingEnabled=false;ctx.drawImage(assets.images.raceProf,r.x,r.y,r.w,r.h,Math.round(sx-dw/2),Math.round(sy-dh),Math.round(dw),Math.round(dh));ctx.restore();return true;}
  function drawEquipment(ctx,n,sx,sy,size){const role=n.roleId||n.professionId||'citizen',g=group(role),seed=hash(n.id||`${n.x}:${n.y}`,81),h=Math.max(7,size);ctx.save();ctx.imageSmoothingEnabled=false;ctx.lineWidth=1;if(g==='field'){ctx.strokeStyle='#8d704b';ctx.beginPath();ctx.moveTo(sx+h*.28,sy-h*.45);ctx.lineTo(sx+h*.5,sy-h*.7);ctx.stroke();}else if(g==='craft'){ctx.fillStyle='#b9a06b';ctx.fillRect(Math.round(sx+h*.34),Math.round(sy-h*.62),2,2);if(seed>.45){ctx.strokeStyle='#c5c5bd';ctx.beginPath();ctx.moveTo(sx+h*.38,sy-h*.42);ctx.lineTo(sx+h*.7,sy-h*.75);ctx.stroke();}}else if(g==='trade'){ctx.fillStyle='#d5b967';ctx.fillRect(Math.round(sx+h*.35),Math.round(sy-h*.55),2,2);}else if(g==='care'){ctx.fillStyle='#79b98c';ctx.fillRect(Math.round(sx+h*.34),Math.round(sy-h*.62),2,2);}else if(g==='military'){ctx.strokeStyle='#c7c7c0';ctx.beginPath();ctx.moveTo(sx+h*.35,sy-h*.25);ctx.lineTo(sx+h*.7,sy-h*.95);ctx.stroke();ctx.fillStyle=seed>.5?'#a33f3f':'#4d657e';ctx.fillRect(Math.round(sx-h*.55),Math.round(sy-h*.72),2,3);}ctx.restore();}
  function draw(){if(!canvas)return;const ctx=canvas.getContext('2d');if(!ctx||!state.camera)return;const z=state.camera.zoom||1,cx=160-state.camera.x*z/8,cy=90-state.camera.y*z/8;(state.npcs||[]).forEach(n=>{if(!n.alive)return;const sx=cx+n.x*z/8,sy=cy+n.y*z/8;if(sx<-16||sx>336||sy<-16||sy>196)return;const scale=(n.visual?.bodyScale||1)*ageScale(n),base=militaryRoles.has(n.roleId)?14:12;drawAsset(ctx,n,sx,sy);drawEquipment(ctx,n,sx,sy,base*scale);});}
  window.EVERGLEN_IDENTITY_VISUALS={bodyProfile,professionVisual};
  registry.register({name:'npc-identity-asset-fidelity',priority:285,draw});
})();
