// Phase 5G: medieval labor markets, wages, employment, apprenticeships and strikes.
(() => {
  const state=window.SIM_STATE;if(!state)return;
  const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,v));
  const alive=()=>state.npcs.filter(n=>n.alive);
  const settlements=()=>state.settlements||[];
  const score=(n,k)=>window.NPC_PERSONALITY?.score?.(n,k)??50;
  const memory=window.NPC_MEMORY;
  const log=t=>window.SIM_API?.log?.(t);
  const JOBS={
    farmer:{base:2,skill:'farming',demand:'food'},hunter:{base:2.2,skill:'farming',demand:'food'},miner:{base:3.2,skill:'mining',demand:'industry'},woodcutter:{base:2.2,skill:'forestry',demand:'wood'},builder:{base:3.4,skill:'construction',demand:'construction'},mason:{base:3.6,skill:'construction',demand:'construction'},carpenter:{base:3.1,skill:'construction',demand:'construction'},blacksmith:{base:4.2,skill:'metallurgy',demand:'industry'},weaver:{base:2.8,skill:'craft',demand:'cloth'},merchant:{base:3.8,skill:'commerce',demand:'trade'},trader:{base:4,skill:'commerce',demand:'trade'},healer:{base:3.5,skill:'medicine',demand:'health'},scholar:{base:3.8,skill:'knowledge',demand:'knowledge'},soldier:{base:2.6,skill:'combat',demand:'military'},knight:{base:4.5,skill:'combat',demand:'military'},engineer:{base:4.6,skill:'engineering',demand:'construction'},shipwright:{base:4.4,skill:'naval',demand:'trade'},alchemist:{base:4.1,skill:'alchemy',demand:'health'},
  };
  function ensure(s){s.labor=s.labor||{workers:0,employed:0,unemployed:0,unfilled:0,wages:0,skillIndex:0,strikePressure:0,history:[]};s.labor.jobs=s.labor.jobs||{};s.labor.apprenticeships=s.labor.apprenticeships||[];s.labor.migrationPressure=s.labor.migrationPressure||0;}
  function skill(n,key){n.skills=n.skills||{};const v=n.skills[key]??(35+score(n,'discipline')*.35+score(n,'learning')*.25);return clamp(v);}
  function targetFor(s,role){const p=alive().filter(n=>n.settlementId===s.id),base=Math.max(1,Math.floor(p.length*(role==='farmer'?.15:['merchant','trader'].includes(role)?.025:.02)));return base;}
  function workforce(s){return alive().filter(n=>n.settlementId===s.id&&n.age>=16&&n.age<=70);}
  function wageFor(n,s){const j=JOBS[n.roleId];if(!j)return .6;ensure(s);const role=JOBS[n.roleId],workers=workforce(s),supply=workers.filter(x=>x.roleId===n.roleId).length,target=targetFor(s,n.roleId);const shortage=clamp((target-supply)/Math.max(1,target),-1,2);const skillPremium=.55+skill(n,role.skill)/130;const market=s.labor.jobs[n.roleId]?.wage||role.base;return Math.max(.4,market*(1+shortage*.65)*skillPremium);}
  function clearMarket(s){ensure(s);const w=workforce(s);const jobs=Object.keys(JOBS);let totalWages=0,unfilled=0,skillTotal=0;
    for(const role of jobs){const target=targetFor(s,role),supply=w.filter(n=>n.roleId===role).length;const shortage=clamp((target-supply)/Math.max(1,target),-1,2);const base=JOBS[role].base;const old=s.labor.jobs[role]?.wage||base;const wage=old*.72+(base*(1+shortage*.7)*(.82+(s.economy?.prosperity||40)/180))*.28;s.labor.jobs[role]={wage:Number(Math.max(.4,wage).toFixed(2)),target,supply,shortage};if(shortage>0)unfilled+=Math.ceil(shortage*target);totalWages+=w.filter(n=>n.roleId===role).length*s.labor.jobs[role].wage;skillTotal+=w.filter(n=>n.roleId===role).reduce((a,n)=>a+skill(n,JOBS[role].skill),0);}
    s.labor.wages=totalWages;s.labor.unfilled=unfilled;s.labor.skillIndex=skillTotal/Math.max(1,w.length);s.labor.workers=w.length;s.labor.employed=w.filter(n=>n.roleId&&JOBS[n.roleId]).length;s.labor.unemployed=Math.max(0,w.length-s.labor.employed);s.labor.employmentRate=s.labor.employed/Math.max(1,w.length)*100;s.labor.unemploymentRate=s.labor.unemployed/Math.max(1,w.length)*100;
  }
  function apprenticeship(s){ensure(s);const p=workforce(s);const masters=p.filter(n=>n.age>=28&&score(n,'discipline')>50&&n.roleId&&JOBS[n.roleId]);const youths=p.filter(n=>n.age>=12&&n.age<20&&!n.roleId&&score(n,'learning')>45);if(!masters.length||!youths.length)return;for(const y of youths.slice(0,3)){const m=masters[Math.floor(Math.random()*masters.length)];const key=JOBS[m.roleId].skill;y.apprenticeTo=m.id;y.apprenticeRole=m.roleId;y.skills[key]=clamp(skill(y,key)+2);s.labor.apprenticeships.push({studentId:y.id,masterId:m.id,role:m.roleId,year:state.year});memory?.remember?.(y,`I began apprenticing as a ${m.roleId}.`,'apprenticeship',2,m.id,'hope');}}
  function trainWorkers(s){const p=workforce(s);p.filter(n=>n.roleId&&JOBS[n.roleId]).slice(0,120).forEach(n=>{const key=JOBS[n.roleId].skill;n.skills=n.skills||{};const gain=.02+.006*score(n,'learning')/100+.004*score(n,'discipline')/100;n.skills[key]=clamp(skill(n,key)+gain*state.speed);n.workSkill=skill(n,key);});}
  function unemploymentBehavior(s){const p=workforce(s),unemp=p.filter(n=>!JOBS[n.roleId]);unemp.forEach(n=>{n.jobSearch=n.jobSearch||{attempts:0,lastRole:null};n.jobSearch.attempts++;if(score(n,'ambition')>60){const candidates=Object.keys(JOBS).sort((a,b)=>Math.abs(targetFor(s,b)-p.filter(x=>x.roleId===b).length)-Math.abs(targetFor(s,a)-p.filter(x=>x.roleId===a).length));const role=candidates[0];if(role&&Math.random()<.08*state.speed){n.roleId=role;n.jobSearch.lastRole=role;memory?.remember?.(n,`I found work as a ${role}.`,'employment',2,s.id,'relief');}}n.grievance=(n.grievance||0)+.015*state.speed;});}
  function strikes(s){ensure(s);const pressure=clamp((s.labor.unemploymentRate||0)*.45+(s.labor.unfilled||0)*.8+(s.marketInflation||0)*20-(s.economy?.prosperity||40)*.18);s.labor.strikePressure=clamp(pressure);if(pressure<38)return;const workers=workforce(s).filter(n=>n.roleId&&JOBS[n.roleId]&&((n.wage||0)<(s.labor.jobs[n.roleId]?.wage||0)*.8||n.grievance>25));if(!workers.length)return;const strike=workers.slice(0,Math.min(12,Math.ceil(workers.length*.35)));s.labor.activeStrike={year:state.year,workers:strike.map(n=>n.id),roleCounts:{}};strike.forEach(n=>{n.onStrike=true;n.grievance=clamp((n.grievance||0)+.08);n.lastAction='On strike';});s.economy&&(s.economy.prosperity=clamp((s.economy.prosperity||40)-.2*strike.length));s.stability=clamp((s.stability||60)-.08);if(state.tick%24===0)log(`${s.name} workers are striking over wages and conditions.`);}
  function resolveStrikes(s){const a=s.labor?.activeStrike;if(!a)return;const workers=alive().filter(n=>a.workers.includes(n.id));if((s.labor.strikePressure||0)<28||Math.random()<.12){workers.forEach(n=>{n.onStrike=false;n.grievance=clamp((n.grievance||0)-1.2);});s.labor.activeStrike=null;}}
  function migrationPressure(s){ensure(s);const push=clamp((s.labor.unemploymentRate||0)*.45+(100-(s.labor.skillIndex||40))*.08-(s.economy?.prosperity||40)*.15,0,60);s.labor.migrationPressure=push;if(push<24)return;const workers=workforce(s).filter(n=>n.age>=18&&n.roleId).sort((a,b)=>(score(b,'adaptability')+score(b,'adventurous'))-(score(a,'adaptability')+score(a,'adventurous')));workers.slice(0,Math.min(2,workers.length)).forEach(n=>{const destinations=settlements().filter(d=>d.id!==s.id).map(d=>({d,score:(d.economy?.prosperity||0)-(d.labor?.unemploymentRate||0)*.6-Math.hypot((d.x||0)-(s.x||0),(d.y||0)-(s.y||0))*.015})).sort((a,b)=>b.score-a.score);const dest=destinations[0]?.d;if(dest&&Math.random()<.08*state.speed){n.settlementId=dest.id;n.laborMigration={from:s.id,to:dest.id,year:state.year};memory?.remember?.(n,`I moved to ${dest.name} to find better work.`,'labor-migration',2,s.id,'hope');}});}
  function productionFeedback(s){const workers=workforce(s).filter(n=>JOBS[n.roleId]);const productivity=workers.reduce((a,n)=>a+skill(n,JOBS[n.roleId].skill),0)/Math.max(1,workers.length);s.labor.productivity=productivity;s.economy=s.economy||{};s.economy.employment=s.labor.employmentRate;s.economy.prosperity=clamp((s.economy.prosperity||40)+(productivity-45)*.008-(s.labor.unemploymentRate||0)*.012);if(s.infrastructure?.workshops&&productivity>60)s.infrastructure.workshops=clamp(s.infrastructure.workshops+.01*state.speed);}
  function step(){if(!state.running)return;settlements().forEach(s=>{ensure(s);clearMarket(s);if(state.tick%30===0)apprenticeship(s);if(state.tick%6===0)trainWorkers(s);if(state.tick%18===0)unemploymentBehavior(s);if(state.tick%24===0)strikes(s);if(state.tick%30===0)resolveStrikes(s);if(state.tick%36===0)migrationPressure(s);productionFeedback(s);s.labor.history.push({year:state.year,employment:Number(s.labor.employmentRate?.toFixed(1)||0),unemployment:Number(s.labor.unemploymentRate?.toFixed(1)||0),skill:Number(s.labor.skillIndex?.toFixed(1)||0),strike:Number(s.labor.strikePressure?.toFixed(1)||0)});s.labor.history=s.labor.history.slice(-24);});}
  window.EVERGLEN_LABOR={step,wageFor,clearMarket,apprenticeship};
  if(state.registerSystem)state.registerSystem({name:'labor-markets',step,priority:72});
})();
