// Phase 5F: medieval land, property and real-estate economy.
(() => {
  const state=window.SIM_STATE;if(!state)return;
  const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,v));
  const alive=()=>state.npcs.filter(n=>n.alive);
  const settlements=()=>state.settlements||[];
  const log=t=>window.SIM_API?.log?.(t);
  const memory=window.NPC_MEMORY;
  const score=(n,k)=>window.NPC_PERSONALITY?.score?.(n,k)??50;
  const roles=new Set(['farmer','rancher','miner','blacksmith','carpenter','weaver','builder','mason','engineer','merchant','trader','shipwright','healer','scholar']);
  const ASSET_TYPES={
    farm:{base:35,rent:.018,yield:.025,inputs:{wood:.2,tools:.08}},
    house:{base:45,rent:.022,yield:0,inputs:{wood:.12,stone:.06}},
    workshop:{base:80,rent:.028,yield:.018,inputs:{wood:.1,iron:.06,tools:.05}},
    shop:{base:110,rent:.032,yield:.012,inputs:{wood:.08,cloth:.04}},
    mine:{base:150,rent:.038,yield:.035,inputs:{tools:.08,wood:.04}},
    estate:{base:300,rent:.045,yield:.04,inputs:{wood:.12,stone:.1,tools:.05}},
    mill:{base:180,rent:.035,yield:.03,inputs:{wood:.12,stone:.08,tools:.04}},
    warehouse:{base:140,rent:.026,yield:.008,inputs:{wood:.12,stone:.05}},
    townhouse:{base:220,rent:.038,yield:0,inputs:{wood:.12,stone:.1}},
    nobleEstate:{base:520,rent:.05,yield:.055,inputs:{wood:.14,stone:.14,tools:.06}}
  };
  function ensureSettlement(s){s.property=s.property||{parcels:[],transactions:[],rentIncome:0,rentPaid:0,ownershipConcentration:0,landValue:0,leases:[]};s.property.parcels=s.property.parcels||[];s.property.transactions=s.property.transactions||[];s.property.leases=s.property.leases||[];}
  function ensureNpc(n){n.property=n.property||{assets:[],land:0,rentIncome:0,rentPaid:0,propertyHistory:[]};}
  function wealth(n){return Math.max(0,(n.wealth||0)+(n.savings||0)-(n.debt||0));}
  function assetValue(asset,s){const t=ASSET_TYPES[asset.type]||ASSET_TYPES.house;const prosperity=(s?.economy?.prosperity||40);const infrastructure=(s?.infrastructure?.roads||0)+(s?.infrastructure?.water||0)*.5;return t.base*(.72+prosperity/180+infrastructure/250);}
  function chooseOwner(s,type){const locals=alive().filter(n=>n.settlementId===s.id&&n.age>=18).sort((a,b)=>wealth(b)-wealth(a));if(!locals.length)return null;const suitable=locals.filter(n=>roles.has(n.roleId));return (suitable.find(n=>wealth(n)>18)||locals.find(n=>wealth(n)>20)||locals[0])||null;}
  function createProperty(s,type,ownerId=null){ensureSettlement(s);if(!ASSET_TYPES[type])return null;const owner=ownerId?alive().find(n=>n.id===ownerId):chooseOwner(s,type);const asset={id:`prop-${s.id}-${state.year}-${s.property.parcels.length}-${Math.floor(Math.random()*1e6)}`,type,ownerId:owner?.id||null,tenantId:null,builtYear:state.year,value:Number(assetValue({type},s).toFixed(2)),rentDue:0,condition:100,status:'owned'};s.property.parcels.push(asset);if(owner){ensureNpc(owner);owner.property.assets.push(asset.id);owner.property.land+=(type==='farm'||type==='estate'||type==='nobleEstate'||type==='mine')?1:0;}return asset;}
  function removeProperty(s,asset){s.property.parcels=s.property.parcels.filter(x=>x.id!==asset.id);if(asset.ownerId){const owner=alive().find(n=>n.id===asset.ownerId);if(owner){ensureNpc(owner);owner.property.assets=owner.property.assets.filter(id=>id!==asset.id);if(['farm','estate','nobleEstate','mine'].includes(asset.type))owner.property.land=Math.max(0,owner.property.land-1);}}}
  function buy(n,s,type){if(!n||!s||!ASSET_TYPES[type])return false;ensureNpc(n);ensureSettlement(s);const price=Number(assetValue({type},s).toFixed(2));if(wealth(n)<price)return false;const asset=createProperty(s,type,n.id);if(!asset)return false;n.wealth=Math.max(0,n.wealth-price);asset.value=price;n.property.propertyHistory.push({year:state.year,action:'purchase',assetId:asset.id,type,price});s.property.transactions.push({year:state.year,action:'purchase',assetId:asset.id,buyerId:n.id,price});return true;}
  function lease(asset,owner,tenant,s){if(!asset||!owner||!tenant)return false;const rent=asset.value*(ASSET_TYPES[asset.type]?.rent||.025);asset.tenantId=tenant.id;asset.rentDue=rent;asset.status='leased';s.property.leases.push({assetId:asset.id,ownerId:owner.id,tenantId:tenant.id,rent,startedYear:state.year});ensureNpc(owner);ensureNpc(tenant);owner.property.rentIncome+=rent;tenant.property.rentPaid+=rent;return true;}
  function transfer(asset,from,to,s,reason='sale'){if(!asset||asset.ownerId!==from.id)return false;ensureNpc(from);ensureNpc(to);const price=asset.value*.92;if(reason==='sale'&&wealth(to)<price)return false;asset.ownerId=to.id;from.property.assets=from.property.assets.filter(id=>id!==asset.id);to.property.assets.push(asset.id);if(['farm','estate','nobleEstate','mine'].includes(asset.type)){from.property.land=Math.max(0,from.property.land-1);to.property.land=(to.property.land||0)+1;}if(reason==='sale'){to.wealth-=price;from.wealth+=price;}to.property.propertyHistory.push({year:state.year,action:'acquired',assetId:asset.id,from:from.id,reason});from.property.propertyHistory.push({year:state.year,action:'transferred',assetId:asset.id,to:to.id,reason});s.property.transactions.push({year:state.year,action:'transfer',assetId:asset.id,from:from.id,to:to.id,reason,price});return true;}
  function inheritance(n,s){ensureNpc(n);const heirs=alive().filter(x=>x.familyId===n.familyId&&x.id!==n.id&&x.age>=18&&x.settlementId===n.settlementId).sort((a,b)=>score(b,'responsibility')-score(a,'responsibility'));if(!heirs.length||!n.property.assets.length)return;const share=n.property.assets.map(id=>s.property.parcels.find(a=>a.id===id)).filter(Boolean);share.forEach((asset,i)=>{const heir=heirs[i%heirs.length];transfer(asset,n,heir,s,'inheritance');});}
  function rentStep(s){ensureSettlement(s);const byId=new Map(alive().map(n=>[n.id,n]));s.property.leases.forEach(l=>{const a=s.property.parcels.find(x=>x.id===l.assetId),o=byId.get(l.ownerId),t=byId.get(l.tenantId);if(!a||!o||!t)return;const rent=Math.min(a.rentDue||a.value*.025,Math.max(0,t.wealth*.06));if(rent>0){t.wealth-=rent;o.wealth+=rent;s.property.rentIncome+=rent;s.property.rentPaid+=rent;l.rentCollected=(l.rentCollected||0)+rent;}else{t.grievance=(t.grievance||0)+.04;}});}
  function propertyProduction(s){ensureSettlement(s);const byId=new Map(alive().map(n=>[n.id,n]));s.property.parcels.forEach(a=>{a.condition=clamp((a.condition??100)-.004*state.speed,0,100);const owner=byId.get(a.ownerId),tenant=byId.get(a.tenantId)||owner;if(!tenant)return;const t=ASSET_TYPES[a.type]||ASSET_TYPES.house;const efficiency=.5+(a.condition/200);const output=(a.value*t.yield*.001*efficiency*state.speed);if(output>0){s.wealth=(s.wealth||0)+output*.25;if(a.type==='farm'||a.type==='estate'||a.type==='nobleEstate')s.resources=s.resources||{},s.resources.food=(s.resources.food||0)+output*.55;if(a.type==='mine')s.resources.iron=(s.resources.iron||0)+output*.25;if(a.type==='workshop'||a.type==='mill')s.resources.tools=(s.resources.tools||0)+output*.18;if(owner){owner.property.rentIncome+=output*.04;owner.economicOutput=(owner.economicOutput||0)+output;}}if(a.condition<30)a.status='dilapidated';});}
  function maintenance(s){ensureSettlement(s);s.property.parcels.forEach(a=>{if(a.condition>72)return;const owner=alive().find(n=>n.id===a.ownerId),cost=a.value*.0018*state.speed;if(owner&&owner.wealth>cost){owner.wealth-=cost;a.condition=clamp(a.condition+5);a.lastMaintainedYear=state.year;}else a.condition=clamp(a.condition-.01*state.speed);});}
  function concentration(s){ensureSettlement(s);const counts={};s.property.parcels.forEach(a=>{if(a.ownerId)counts[a.ownerId]=(counts[a.ownerId]||0)+1;});const total=s.property.parcels.length;const top=Object.values(counts).sort((a,b)=>b-a).slice(0,3).reduce((x,v)=>x+v,0);s.property.ownershipConcentration=total?clamp(top/total*100):0;s.property.landValue=s.property.parcels.reduce((a,x)=>a+x.value,0);s.property.topOwners=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([id,count])=>({id,count}));}
  function estateMobility(s){ensureSettlement(s);const locals=alive().filter(n=>n.settlementId===s.id&&n.age>=18);locals.slice(0,Math.min(60,locals.length)).forEach(n=>{ensureNpc(n);const tier=wealth(n);if(!n.property.assets.length&&tier>90&&Math.random()<.008*state.speed){const type=['house','workshop','shop','farm'][Math.floor(Math.random()*4)];buy(n,s,type);}if(n.property.assets.length&&tier<20&&Math.random()<.01*state.speed){const a=s.property.parcels.find(x=>x.ownerId===n.id);const buyer=locals.find(x=>x.id!==n.id&&wealth(x)>a?.value);if(a&&buyer)transfer(a,n,buyer,s,'distress-sale');}});}
  function classFeedback(s){ensureSettlement(s);const locals=alive().filter(n=>n.settlementId===s.id);const owners=locals.filter(n=>n.property.assets.length>0);s.property.ownerRate=locals.length?owners.length/locals.length*100:0;owners.forEach(n=>{n.propertyWealth=(n.property.assets||[]).reduce((sum,id)=>{const a=s.property.parcels.find(x=>x.id===id);return sum+(a?.value||0);},0);n.landPower=clamp(n.propertyWealth*.035+n.property.assets.length*1.5);if(n.landPower>45)n.influence=(n.influence||0)+.006*state.speed;});if(s.property.ownershipConcentration>65){s.economy=s.economy||{};s.economy.prosperity=clamp((s.economy.prosperity||40)+.03*state.speed);}if(s.property.ownershipConcentration>78)s.stability=clamp((s.stability||60)-.02*state.speed);}
  function step(){if(!state.running)return;settlements().forEach(ensureSettlement);alive().forEach(ensureNpc);if(state.tick%24===0)settlements().forEach(s=>{const p=alive().filter(n=>n.settlementId===s.id);if(s.property.parcels.length<Math.max(8,p.length*.45)){const type=p.length>18?'house':p.length>8?'farm':'house';createProperty(s,type);}});if(state.tick%12===0)settlements().forEach(rentStep);if(state.tick%8===0)settlements().forEach(propertyProduction);if(state.tick%20===0)settlements().forEach(maintenance);if(state.tick%24===0)settlements().forEach(concentration);if(state.tick%30===0)settlements().forEach(estateMobility);if(state.tick%36===0)settlements().forEach(classFeedback);}
  window.EVERGLEN_PROPERTY={step,buy,lease,transfer,inheritance,createProperty,assetValue};
  if(state.registerSystem)state.registerSystem({name:'land-property',step,priority:70});
})();
