// Phase 5C: medieval banking, credit, savings, investment and wealth stratification.
(() => {
  const state=window.SIM_STATE;if(!state)return;
  const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,v));
  const alive=()=>state.npcs.filter(n=>n.alive);
  const settlements=()=>state.settlements||[];
  const log=t=>window.SIM_API?.log?.(t);
  const memory=window.NPC_MEMORY;
  const score=(n,k)=>window.NPC_PERSONALITY?.score?.(n,k)??50;
  const has=(n,t)=>window.NPC_PERSONALITY?.has?.(n,t)||n.trait===t||n.traits?.includes(t);
  const ensureSettlement=s=>{s.finance=s.finance||{banks:[],loans:[],savings:[],defaults:0,interestIncome:0,creditVolume:0,history:[]};s.finance.reserve=s.finance.reserve??Math.max(30,(s.wealth||0)*.18+20);s.finance.creditRate=s.finance.creditRate??.08;s.finance.trust=s.finance.trust??50;};
  const ensureNpc=n=>{n.wealth=Math.max(0,n.wealth||0);n.debt=Math.max(0,n.debt||0);n.savings=Math.max(0,n.savings||0);n.creditScore=n.creditScore??55;n.finance=n.finance||{loans:[],interestEarned:0,interestPaid:0,businessCapital:0};};
  function wealthTier(n){const w=n.wealth+n.savings-n.debt;return w<10?'destitute':w<35?'poor':w<90?'working':w<220?'comfortable':w<500?'wealthy':'elite';}
  function classMobility(n){const tier=wealthTier(n),old=n.wealthClass;if(old!==tier){n.wealthClass=tier;n.finance.mobilityHistory=n.finance.mobilityHistory||[];n.finance.mobilityHistory.push({year:state.year,from:old||null,to:tier});n.finance.mobilityHistory=n.finance.mobilityHistory.slice(-20);if(memory?.experience&&old)memory.experience(n,`My fortunes changed from ${old} to ${tier}.`,'wealth-mobility',2,null,tier==='wealthy'||tier==='elite'?'pride':'fear',0,false);}}
  function establishBank(s){ensureSettlement(s);if(s.finance.banks.length)return s.finance.banks[0];const bank={id:`bank-${s.id}`,name:`${s.name} Exchange`,capital:Math.max(50,(s.wealth||0)*.12),reserve:s.finance.reserve,rate:s.finance.creditRate,trust:s.finance.trust,profit:0,loans:0,defaults:0};s.finance.banks.push(bank);return bank;}
  function creditLimit(n,s){ensureNpc(n);ensureSettlement(s);const tier=wealthTier(n),base={destitute:4,poor:9,working:22,comfortable:55,wealthy:120,elite:300}[tier];const trust=clamp((s.finance.trust||50)/50,.35,1.8);const scoreFactor=clamp((n.creditScore||50)/55,.4,1.7);return base*trust*scoreFactor;}
  function lend(n,s,amount,purpose='working-capital'){
    if(!n||!s)return false;ensureNpc(n);ensureSettlement(s);const bank=establishBank(s);const available=Math.max(0,bank.reserve-(s.finance.reserve*.25));const max=Math.min(creditLimit(n,s),available);const principal=Math.min(Math.max(0,amount),max);if(principal<1)return false;const due=principal*(1+bank.rate);const loan={id:`loan-${s.id}-${state.year}-${Math.floor(Math.random()*1e6)}`,borrowerId:n.id,principal,balance:due,rate:bank.rate,purpose,startedYear:state.year,dueYear:state.year+3,paid:0,status:'active'};s.finance.loans.push(loan);n.finance.loans.push(loan.id);n.debt+=principal;n.wealth+=principal;bank.reserve-=principal;bank.loans+=principal;s.finance.creditVolume+=principal;return true;}
  function repay(n,s,loan){if(!loan||loan.status!=='active')return false;ensureNpc(n);const payment=Math.min(loan.balance,Math.max(.6,n.wealth*.08));if(n.wealth<payment)return false;n.wealth-=payment;loan.balance-=payment;loan.paid+=payment;n.finance.interestPaid=(n.finance.interestPaid||0)+Math.max(0,payment-loan.principal);n.debt=Math.max(0,n.debt-payment);const bank=establishBank(s);bank.reserve+=payment;s.finance.creditVolume=Math.max(0,s.finance.creditVolume-payment);if(loan.balance<=.01){loan.status='repaid';n.creditScore=clamp(n.creditScore+8);memory?.experience?.(n,'I repaid a loan and strengthened my standing.','credit-success',2,s.id,'pride',-2,false);}return true;}
  function defaultLoan(n,s,loan){loan.status='defaulted';ensureSettlement(s);const bank=establishBank(s);bank.defaults++;s.finance.defaults++;n.creditScore=clamp(n.creditScore-18);n.grievance=(n.grievance||0)+1.5;n.debt=Math.max(0,n.debt-loan.balance*.35);loan.balance=0;memory?.experience?.(n,'I could not repay my debt.','credit-default',4,s.id,'fear',5,true);if(Math.random()<.35){n.crimeHeat=(n.crimeHeat||0)+2;n.lastAction='Desperate to settle debt';}}
  function invest(n,s){if(!n||!s)return false;ensureNpc(n);const bank=establishBank(s);const amount=Math.min(n.wealth*.08,Math.max(2,bank.capital*.04));if(amount<2||n.wealth<amount+5)return false;n.wealth-=amount;n.savings+=amount;n.finance.interestEarned+=amount*.018;bank.reserve+=amount;bank.capital+=amount*.7;return true;}
  function financeStep(n){ensureNpc(n);const s=settlements().find(x=>x.id===n.settlementId);if(!s||n.age<16)return;ensureSettlement(s);classMobility(n);if(state.tick%36===0){if(n.wealth>45&&(has(n,'cautious')||score(n,'risk')<40))invest(n,s);if(n.wealth<5&&n.debt<creditLimit(n,s)*.65&&score(n,'risk')>35)lend(n,s,Math.min(creditLimit(n,s),8+score(n,'ambition')*.15),'household');if(n.business&&n.business.capital<80&&score(n,'ambition')>55)lend(n,s,Math.min(creditLimit(n,s),15),'business-capital');}if(state.tick%18===0){const loans=s.finance.loans.filter(x=>x.borrowerId===n.id&&x.status==='active');loans.forEach(loan=>{if(n.wealth>loan.balance*.18)repay(n,s,loan);else if(state.year>loan.dueYear&&Math.random()<.12)defaultLoan(n,s,loan);});}n.savings=Math.max(0,n.savings*(1+.0015*state.speed));n.wealthClass=wealthTier(n);}
  function settlementFinance(s){ensureSettlement(s);const bank=establishBank(s);const pop=Math.max(1,alive().filter(n=>n.settlementId===s.id).length);const locals=alive().filter(n=>n.settlementId===s.id);const wealth=locals.reduce((a,n)=>a+n.wealth+n.savings,0);const debt=locals.reduce((a,n)=>a+n.debt,0);bank.capital=Math.max(bank.capital*.995,(wealth*.08)+50);bank.trust=clamp(50+(s.stability||60)*.22-(s.finance.defaults||0)*1.8);bank.rate=clamp(.065+(100-bank.trust)*.0015,.05,.16);s.finance.creditRate=bank.rate;s.finance.reserve=Math.max(10,bank.reserve+bank.capital*.002-(debt*.001));s.finance.interestIncome=(s.finance.interestIncome||0)+s.finance.loans.filter(l=>l.status==='repaid').length*.01;s.finance.history.push({year:state.year,capital:Number(bank.capital.toFixed(2)),debt:Number(debt.toFixed(2)),trust:Number(bank.trust.toFixed(1)),rate:Number(bank.rate.toFixed(3))});s.finance.history=s.finance.history.slice(-30);const counts={destitute:0,poor:0,working:0,comfortable:0,wealthy:0,elite:0};locals.forEach(n=>counts[wealthTier(n)]++);s.finance.wealthDistribution=counts;s.finance.debtPerCapita=debt/pop;s.finance.savingsPerCapita=locals.reduce((a,n)=>a+n.savings,0)/pop;s.finance.bankHealth=clamp((bank.reserve+bank.capital*.5)/(50+debt)*100);}
  function kingdomFinance(){state.kingdoms?.forEach(k=>{const locals=settlements().filter(s=>s.kingdomId===k.id);const total=locals.reduce((a,s)=>a+(s.finance?.creditVolume||0),0);k.finance=k.finance||{creditVolume:0,bankingPower:0,wealth:0};k.finance.creditVolume=total;k.finance.bankingPower=clamp(locals.reduce((a,s)=>a+(s.finance?.bankHealth||0),0)/Math.max(1,locals.length));k.finance.wealth=locals.reduce((a,s)=>a+(s.wealth||0),0);k.finance.taxBase=clamp(k.finance.wealth*.02+k.finance.creditVolume*.015);if(k.politics)k.politics.wealthPower=clamp((k.politics.wealthPower||0)+k.finance.bankingPower*.01);});}
  function step(){if(!state.running)return;settlements().forEach(ensureSettlement);alive().forEach(financeStep);if(state.tick%12===0)settlements().forEach(settlementFinance);if(state.tick%24===0)kingdomFinance();}
  window.EVERGLEN_BANKING={step,lend,repay,defaultLoan,invest,wealthTier,creditLimit,establishBank};
  if(state.registerSystem)state.registerSystem({name:'banking-credit',step,priority:54});
})();
