// Phase 3K: player-facing geopolitical controls.
// State mutation is attributed through the shared player event pipeline; no DOM ownership here.
(() => {
  const state=window.SIM_STATE;if(!state)return;
  const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,v));
  const key=(a,b)=>[String(a),String(b)].sort().join(':');
  const event=(type,payload)=>window.PLAYER_EVENT_PIPELINE?.record?.(type,payload)||window.PLAYER_EVENT_PIPELINE?.remember?.(payload?.npc,payload?.text||type,type,4,payload?.targetId,'power');
  function kingdom(id){return state.kingdoms.find(k=>String(k.id)===String(id))||null}
  function treaty(type,a,b,years=8){const existing=(state.diplomacy?.treaties||[]).find(t=>t.status==='active'&&t.type===type&&key(t.a,t.b)===key(a,b));if(existing)return existing;state.diplomacy=state.diplomacy||{relations:{},treaties:[],history:[]};state.diplomacy.treaties.push({id:`player-dip-${Date.now()}`,type,a,b,startYear:state.year,endYear:state.year+years,status:'active',playerCreated:true});state.diplomacy.history.push({year:state.year,type,a,b,player:true});event('player-diplomacy',{action:'force-treaty',type,targetId:b,text:`The player imposed a ${type} between the realms.`});return state.diplomacy.treaties.at(-1)}
  function setRelation(a,b,delta){state.diplomacy=state.diplomacy||{relations:{},treaties:[],history:[]};state.diplomacy.relations=state.diplomacy.relations||{};const r=state.diplomacy.relations[key(a,b)]||{a:String(a),b:String(b),score:0,trust:35,hostility:0,trade:0};r.score=clamp((r.score||0)+delta,-100,100);r.trust=clamp((r.trust||35)+delta*.3);state.diplomacy.relations[key(a,b)]=r;const ka=kingdom(a);if(ka?.diplomacy)ka.diplomacy.relations[String(b)]=r;event('player-diplomacy',{action:'change-relation',targetId:b,text:`The player altered relations between ${ka?.name||a} and the other realm.`});return r}
  function triggerPressure(id,amount=20){const k=kingdom(id);if(!k)return null;k.tension=clamp((k.tension||0)+amount);k.stability=clamp((k.stability||70)-amount*.25);k.society=k.society||{};k.society.unrest=k.society.unrest||{};k.society.unrest.pressure=clamp((k.society.unrest.pressure||0)+amount);event('player-political-pressure',{action:'political-pressure',targetId:id,text:`The player increased political pressure inside ${k.name}.`});return k}
  function supportClaimant(kingdomId,npcId){const k=kingdom(kingdomId),n=state.npcs.find(x=>String(x.id)===String(npcId));if(!k||!n)return null;k.dynasticGeopolitics=k.dynasticGeopolitics||{claimants:[],marriages:[],backers:{},history:[]};k.dynasticGeopolitics.backers[n.id]=k.dynasticGeopolitics.backers[n.id]||[];k.dynasticGeopolitics.backers[n.id].push({year:state.year,player:true});n.influence=clamp((n.influence||0)+8);n.reputation=clamp((n.reputation||50)+5);event('player-claimant-support',{action:'support-claimant',targetId:n.id,npc:n,text:`The player backed ${n.name} as a political claimant.`});return n}
  function recognizeIndependence(id){const k=kingdom(id);if(!k)return null;k.independent=true;k.occupation=null;k.parentKingdomId=null;event('player-independence',{action:'recognize-independence',targetId:id,text:`The player recognized ${k.name} as an independent realm.`});return k}
  function inspect(id){const k=kingdom(id);if(!k)return null;return {name:k.name,strategy:k.strategy||null,geopolitics:k.geopolitics||null,warPlan:k.warPlan||null,diplomacy:k.diplomacy||null,international:k.international||null,occupation:k.occupation||null,dynasticGeopolitics:k.dynasticGeopolitics||null};}
  window.PLAYER_GEOPOLITICS={inspect,forceAlliance:(a,b)=>treaty('alliance',a,b,12),forceTradePact:(a,b)=>treaty('trade-pact',a,b,8),forceTruce:(a,b)=>treaty('truce',a,b,4),changeRelation:setRelation,triggerPressure,supportClaimant,recognizeIndependence};
})();
