(() => {
  const RESOURCES = ['food','wood','stone','iron','gold','cloth','medicine','reagents','weapons','armor','tools'];
  const NAMES = ['Ari','Bram','Cora','Dax','Elia','Faye','Gale','Hana','Ivo','Juno','Kian','Lena','Milo','Nia','Oren','Pia','Quill','Rhea','Sera','Tobin','Uma','Vale','Wren','Yara','Zane','Mara','Theo','Niko','Lumi','Cass','Dara','Soren','Vera','Kato','Mira','Rowan','Orin','Lyra','Finn','Nora','Rin','Alden','Talia','Marek','Eira','Corin'];
  const TRAITS = ['brave','curious','ambitious','kind','greedy','loyal','stubborn','clever','reckless','calm'];
  const COLORS = ['#79c2ff','#ff9f7a','#a8e68a','#d7a7ff','#ffd66e','#ff8fc8'];
  const ROLES = {
    farmer:['Farmer',3], miner:['Miner',2], woodcutter:['Woodcutter',3], builder:['Builder',2], blacksmith:['Blacksmith',3], armorer:['Armorer',3], carpenter:['Carpenter',2], weaver:['Weaver',2], baker:['Baker',1], cook:['Cook',1], healer:['Healer',2], merchant:['Merchant',3], trader:['Trader',3], shipwright:['Shipwright',4], sailor:['Sailor',2], scholar:['Scholar',3], teacher:['Teacher',2], engineer:['Engineer',4], architect:['Architect',4], hunter:['Hunter',2], forager:['Forager',1], thief:['Thief',2], burglar:['Burglar',2], bandit:['Bandit',3], smuggler:['Smuggler',4], spy:['Spy',4], militia:['Militia',2], soldier:['Soldier',3], archer:['Archer',3], spearman:['Spearman',3], cavalry:['Cavalry',4], knight:['Knight',5], paladin:['Paladin',6], ranger:['Ranger',4], captain:['Captain',6], general:['General',8], marshal:['Marshal',9], bodyguard:['Bodyguard',5], acolyte:['Acolyte',2], cleric:['Cleric',4], priest:['Priest',5], high_priest:['High Priest',7], monk:['Monk',3], oracle:['Oracle',6], druid:['Druid',5], mage:['Mage',6], wizard:['Wizard',8], sorcerer:['Sorcerer',7], alchemist:['Alchemist',5], enchanter:['Enchanter',7], necromancer:['Necromancer',8], mayor:['Mayor',5], baron:['Baron',8], count:['Count',9], duke:['Duke',11], prince:['Prince',13], king:['King',15], emperor:['Emperor',18], heir:['Heir',12], chancellor:['Chancellor',10], citizen:['Citizen',1], student:['Student',1], child:['Child',0], elder:['Elder',1], refugee:['Refugee',1], prisoner:['Prisoner',0], rebel:['Rebel',3]
  };
  const BUILDINGS = {
    house:{wood:8,stone:2,gold:1}, farm:{wood:5,stone:1,tools:1}, mine:{wood:8,stone:8,tools:2}, lumberyard:{wood:4,stone:3,tools:1}, smithy:{wood:10,stone:8,iron:3,tools:1}, market:{wood:10,stone:6,gold:4}, temple:{stone:15,wood:8,gold:5}, barracks:{stone:16,wood:10,iron:3,weapons:2}, castle:{stone:60,wood:25,iron:12,gold:20}, library:{wood:12,stone:12,gold:8,cloth:4}, wizard_tower:{stone:22,wood:10,reagents:5,gold:10}, dock:{wood:22,stone:8,tools:3}, prison:{stone:18,iron:6,wood:8}, workshop:{wood:12,stone:8,tools:2}
  };
  const ROLE_OUTPUT = {
    farmer:{food:3}, miner:{iron:2,stone:1}, woodcutter:{wood:3}, forager:{food:2}, hunter:{food:2}, fisher:{food:2}, mason:{stone:2}, blacksmith:{weapons:1,tools:1,iron:-2}, armorer:{armor:1,iron:-2}, carpenter:{tools:1,wood:-2}, weaver:{cloth:2}, baker:{food:4}, cook:{food:2}, healer:{medicine:1}, doctor:{medicine:1}, merchant:{gold:1}, trader:{gold:2}, shipwright:{wood:-3,tools:-1}, sailor:{gold:1}, alchemist:{medicine:1,reagents:-1}, enchanter:{armor:1,reagents:-2}, mage:{reagents:-1}, wizard:{reagents:-2}, cleric:{medicine:1}, druid:{food:1,medicine:1}, thief:{gold:1}, smuggler:{gold:2}, bandit:{gold:1}, farmer:{food:3}, soldier:{food:-1,weapons:-.2,armor:-.1}, archer:{food:-1,weapons:-.2}, spearman:{food:-1,weapons:-.2}, knight:{food:-1,weapons:-.3,armor:-.2}, cavalry:{food:-1,weapons:-.35,armor:-.3}, captain:{food:-1,weapons:-.2,armor:-.2}, general:{food:-1}, marshal:{food:-1}
  };

  const state = {
    running:true,tick:0,year:1,day:1,hour:8,season:'Spring',speed:4,weather:'Clear',food:65,stability:82,war:false,plague:false,godMode:false,
    showNames:true,showGrid:false,showTrails:false,selected:null,feed:[],micro:[],npcs:[],families:[],clans:[],kingdoms:[],settlements:[],counties:[],duchies:[],roads:[],caravans:[],armies:[],particles:[],camera:{x:0,y:0,zoom:1},dragging:false,dragStart:null,lastSimTime:0
  };
  const canvas=document.getElementById('worldCanvas'), ctx=canvas.getContext('2d');
  const $=id=>document.getElementById(id);
  const el={toggleSim:$('toggleSim'),speed:$('speed'),speedLabel:$('speedLabel'),year:$('year'),season:$('season'),population:$('population'),families:$('families'),settlements:$('settlements'),food:$('food'),stability:$('stability'),worldStatus:$('worldStatus'),worldStats:$('worldStats'),factionList:$('factionList'),eventFeed:$('eventFeed'),microLog:$('microLog'),inspectorContent:$('inspectorContent'),needsChart:$('needsChart'),selectedNeedMood:$('selectedNeedMood'),tickLabel:$('tickLabel'),modeLabel:$('modeLabel')};
  const W=1400,H=1000;

  function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
  function pick(a){return a[Math.floor(Math.random()*a.length)];}
  function uid(){return Math.random().toString(36).slice(2)+Date.now().toString(36);}
  function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y);}
  function alive(){return state.npcs.filter(n=>n.alive);}
  function log(m){state.feed.unshift(`Year ${state.year}, Day ${state.day}: ${m}`);state.feed=state.feed.slice(0,15);el.eventFeed.innerHTML=state.feed.map(x=>`<li>${x}</li>`).join('');}
  function micro(m){state.micro.unshift(m);state.micro=state.micro.slice(8);el.microLog.innerHTML=state.micro.map(x=>`<div>${x}</div>`).join('');}
  function memory(n,text){n.memories.unshift({year:state.year,text});n.memories=n.memories.slice(0,8);}
  function faction(npc){return state.kingdoms.find(k=>k.id===npc.faction)||null;}
  function settlement(npc){return state.settlements.find(s=>s.id===npc.settlementId)||null;}
  function family(npc){return state.families.find(f=>f.id===npc.familyId)||null;}

  function createKingdom(name='Freefolk'){const k={id:uid(),name,color:COLORS[state.kingdoms.length%COLORS.length],population:0,capitalId:null,leaderId:null,taxRate:.08,treasury:100,power:25,stability:82};state.kingdoms.push(k);return k;}
  function createFamily(seed){const f={id:uid(),name:`${seed} Family`,members:[],wealth:0,legacy:0,deadMembers:0};state.families.push(f);return f;}
  function createClan(f){const c={id:uid(),name:`Clan ${f.name.split(' ')[0]}`,familyIds:[f.id],influence:10};state.clans.push(c);f.clanId=c.id;return c;}
  function createNpc(i, kingdomId){const n={id:i+1,name:NAMES[i%NAMES.length]+(i>=NAMES.length?` ${Math.floor(i/NAMES.length)+1}`:''),age:18+Math.floor(Math.random()*33),sex:Math.random()>.5?'F':'M',trait:pick(TRAITS),roleId:'citizen',roleName:'Citizen',faction:kingdomId,settlementId:null,x:Math.random()*W-W/2,y:Math.random()*H-H/2,target:null,speed:.45+Math.random()*.55,mood:65,health:100,hunger:15+Math.random()*25,energy:70+Math.random()*30,wealth:20+Math.random()*80,goal:'Explore',home:null,partnerId:null,parentIds:[],childrenIds:[],friends:[],enemies:[],memories:[],alive:true,color:pick(COLORS),inventory:Object.fromEntries(RESOURCES.map(r=>[r,0]))};return n;}

  function createSettlement(name,x,y,type='village',kingdomId=null,founder=null){const s={id:uid(),name,type,level:type==='village'?1:type==='city'?2:3,x,y,radius:type==='village'?85:type==='city'?135:210,kingdomId,founderId:founder?.id||null,rulerId:founder?.id||null,age:0,homes:type==='village'?5:type==='city'?18:60,buildings:type==='village'?2:type==='city'?7:24,military:0,stability:78,wealth:150,resources:{food:55,wood:50,stone:30,iron:8,gold:25,cloth:7,medicine:2,reagents:2,weapons:0,armor:0,tools:5},history:[`Year ${state.year}: founded.`]};state.settlements.push(s);return s;}
  function makeCounty(s){const c={id:uid(),name:`County of ${s.name}`,settlementId:s.id,kingdomId:s.kingdomId,countId:null,radius:190+Math.random()*80,center:{x:s.x,y:s.y},taxRate:.08,development:20};state.counties.push(c);return c;}
  function makeDuchy(counties){const first=counties[0];const d={id:uid(),name:`Duchy of ${first?.name?.replace(/^County of /,'')||'the Marches'}`,kingdomId:first?.kingdomId||null,dukeId:null,countyIds:counties.map(c=>c.id),radius:360,stability:75};state.duchies.push(d);return d;}
  function makeRoad(a,b,kind='road'){const r={id:uid(),from:a.id,to:b.id,kind,length:Math.max(40,dist(a,b)),condition:100,capacity:2};state.roads.push(r);return r;}
  function makeArmy(kingdomId,x,y){const a={id:uid(),kingdomId,x,y,target:null,soldiers:20,supply:100,morale:85,active:false};state.armies.push(a);return a;}
  function makeCaravan(road){const a=state.settlements.find(s=>s.id===road.from),b=state.settlements.find(s=>s.id===road.to);if(!a||!b)return;state.caravans.push({id:uid(),roadId:road.id,x:a.x,y:a.y,progress:0,from:a.id,to:b.id,cargo:{food:4,wood:2,iron:1,gold:0},speed:.006+Math.random()*.004,profit:0});}

  function reset(){
    state.tick=0;state.year=1;state.day=1;state.hour=8;state.season='Spring';state.weather='Clear';state.food=65;state.stability=82;state.war=false;state.plague=false;state.selected=null;state.families=[];state.clans=[];state.kingdoms=[];state.settlements=[];state.counties=[];state.duchies=[];state.roads=[];state.caravans=[];state.armies=[];state.npcs=[];
    const k=createKingdom();
    state.npcs=Array.from({length:72},(_,i)=>createNpc(i,k.id));
    const founder=state.npcs[0]; founder.trait='ambitious';founder.x=0;founder.y=0;founder.roleId='mayor';founder.roleName='Mayor';founder.wealth=140;founder.goal='Find a place to settle';
    const f=createFamily(founder.name);createClan(f);state.npcs.slice(0,8).forEach(n=>{n.familyId=f.id;n.familyName=f.name;f.members.push(n.id);});
    const s=createSettlement('Everglen',0,0,'village',k.id,founder);k.capitalId=s.id;k.leaderId=founder.id;
    state.npcs.slice(0,8).forEach(n=>{n.settlementId=s.id;n.home=s.name;n.x+=Math.random()*80-40;n.y+=Math.random()*80-40;});
    state.npcs.slice(8).forEach((n,i)=>{n.x=(Math.random()>.5?1:-1)*(120+Math.random()*430);n.y=(Math.random()>.5?1:-1)*(80+Math.random()*330);});
    makeCounty(s);log('The first settlers enter an untouched land.');log(`${founder.name} is recognized as the founding leader of Everglen.`);micro('WORLD RESET');render();
  }

  function roleFor(n,i){if(n.age<13)return ['child','Child'];if(n.age<18)return ['student','Student'];if(n.roleId&&n.roleId!=='citizen')return [n.roleId,n.roleName];const pool=['farmer','miner','woodcutter','builder','blacksmith','merchant','trader','healer','hunter','scholar'];let r=pool[i%pool.length];if(n.trait==='greedy')r=pick(['merchant','trader']);if(n.trait==='brave')r=Math.random()<.4?'soldier':r;if(n.trait==='curious'&&Math.random()<.18)r='scholar';return [r,ROLES[r][0]];}
  function assignRoles(){alive().forEach((n,i)=>{const [id,name]=roleFor(n,i);n.roleId=id;n.roleName=name;});
    state.kingdoms.forEach(k=>{const g=alive().filter(n=>n.faction===k.id);if(!g.length)return;const sorted=[...g].sort((a,b)=>(b.wealth+b.age+b.mood)-(a.wealth+a.age+a.mood));const king=sorted.find(n=>n.id===k.leaderId)||sorted[0];if(g.length>=55){king.roleId='king';king.roleName='King';k.leaderId=king.id;}if(g.length>=25)sorted.slice(1,3).forEach(n=>{n.roleId='duke';n.roleName='Duke';});if(g.length>=12)sorted.slice(3,6).forEach(n=>{n.roleId='count';n.roleName='Count';});const brave=g.filter(n=>['brave','reckless','loyal'].includes(n.trait)&&n.age>18);brave.slice(0,Math.max(2,Math.floor(g.length*.1))).forEach((n,i)=>{if(!['king','duke','count'].includes(n.roleId)){n.roleId=i===0?'captain':'soldier';n.roleName=ROLES[n.roleId][0];}});const calm=g.find(n=>n.trait==='calm'&&n.age>20);if(calm&&g.length>=10&&!['king','duke','count'].includes(calm.roleId)){calm.roleId='cleric';calm.roleName='Cleric';}const curious=g.find(n=>n.trait==='curious'&&n.age>24);if(curious&&g.length>=20){curious.roleId='wizard';curious.roleName='Wizard';}if(k.stability<50){const thief=g.find(n=>n.trait==='greedy'&&n.age>18);if(thief){thief.roleId='thief';thief.roleName='Thief';}}});
  }

  function adoptSettlement(n){if(n.settlementId)return;const s=state.settlements.slice().sort((a,b)=>dist(n,a)-dist(n,b))[0];if(s&&dist(n,s)<s.radius*1.25)n.settlementId=s.id;n.home=s?.name||null;}
  function foundVillage(){if(state.settlements.length)return;const founder=state.npcs[0];if(state.day<2||!founder?.alive)return;const settlers=alive().filter(n=>n.id!==founder.id).sort((a,b)=>dist(a,founder)-dist(b,founder)).slice(0,7);if(settlers.length>=7){const s=createSettlement(`${founder.name}'s Haven`,founder.x,founder.y,'village',founder.faction,founder);const fam=family(founder);settlers.forEach(n=>{n.settlementId=s.id;n.home=s.name;fam.members.push(n.id);n.familyId=fam.id;n.x=s.x+Math.random()*70-35;n.y=s.y+Math.random()*70-35;});makeCounty(s);const k=faction(founder);k.capitalId=s.id;log(`${founder.name} founded the village of ${s.name}.`);micro(`FOUNDING ${s.name}`);}}

  function produce(s){const people=state.npcs.filter(n=>n.alive&&n.settlementId===s.id);const res=s.resources;people.forEach(n=>{const out=ROLE_OUTPUT[n.roleId];if(!out)return;Object.entries(out).forEach(([r,v])=>{if(v>0)res[r]=(res[r]||0)+v*.035*state.speed;else res[r]=Math.max(0,(res[r]||0)+v*.02*state.speed);});n.hunger=clamp(n.hunger+.015*state.speed,0,100);});
    const houses=Math.max(1,s.homes);res.food=Math.max(0,res.food-people.length*.015*state.speed);s.food=res.food;s.wealth+=Math.max(0,people.filter(n=>['merchant','trader'].includes(n.roleId)).length*.03*state.speed);s.stability=clamp(s.stability+(res.food>25?.01:-.04),0,100);s.homes=Math.max(s.homes,Math.floor(people.length/2));s.buildings=Math.max(s.buildings,Math.floor(s.homes/2));
  }
  function buildings(s){const desired=[];const p=state.npcs.filter(n=>n.alive&&n.settlementId===s.id);if(p.length>s.homes*.8)desired.push('house');if(p.some(n=>n.roleId==='farmer'))desired.push('farm');if(p.some(n=>n.roleId==='miner'))desired.push('mine');if(p.some(n=>n.roleId==='blacksmith'||n.roleId==='armorer'))desired.push('smithy');if(p.some(n=>n.roleId==='merchant'||n.roleId==='trader'))desired.push('market');if(p.some(n=>n.roleId==='cleric'))desired.push('temple');if(p.some(n=>['soldier','knight','captain'].includes(n.roleId)))desired.push('barracks');if(p.some(n=>n.roleId==='wizard'))desired.push('wizard_tower');if(p.some(n=>n.roleId==='scholar'))desired.push('library');if(p.some(n=>n.roleId==='shipwright'||n.roleId==='sailor'))desired.push('dock');s.buildings=Math.max(s.buildings,Math.min(40,s.buildings+Math.min(desired.length,3)*.004*state.speed));}

  function upgrade(s){const p=state.npcs.filter(n=>n.alive&&n.settlementId===s.id),ad=p.filter(n=>n.age>=18);if(s.type==='village'&&p.length>=30&&ad.length>=18&&s.resources.food>=60&&s.homes>=15&&s.buildings>=6&&s.age>=4){s.type='city';s.level=2;s.radius=140;s.history.push(`Year ${state.year}: became a city.`);log(`${s.name} grew into a CITY.`);micro(`CITY ${s.name}`);}
    if(s.type==='city'&&p.length>=90&&s.resources.food>=75&&s.homes>=35&&s.buildings>=16&&s.stability>=65&&state.settlements.length>=2){s.type='kingdom';s.level=3;s.radius=230;s.history.push(`Year ${state.year}: became a kingdom.`);const k=faction(p[0]);k.name=`Kingdom of ${s.name}`;k.capitalId=s.id;k.leaderId=s.rulerId||p[0].id;p.forEach(n=>n.faction=k.id);log(`${s.name} has become a KINGDOM under ${p[0].name}.`);micro(`KINGDOM ${s.name}`);}}
  function spawnExpansion(s){if(s.type!=='city'||state.settlements.filter(x=>x.kingdomId===s.kingdomId).length>=3)return;if(state.year<5||Math.random()>.002*state.speed)return;const x=s.x+260+Math.random()*120,y=s.y+120+Math.random()*110;const v=createSettlement(`${pick(NAMES)} Reach`,x,y,'village',s.kingdomId,null);makeCounty(v);const pioneer=state.npcs.filter(n=>n.alive&&n.settlementId===s.id&&n.trait==='ambitious')[0];if(pioneer){pioneer.settlementId=v.id;pioneer.home=v.name;log(`${pioneer.name} founded ${v.name}, extending the realm.`);}}
  function hierarchy(){state.settlements.forEach(s=>{s.age+=.002*state.speed;upgrade(s);buildings(s);spawnExpansion(s);});state.counties.forEach(c=>{const s=state.settlements.find(x=>x.id===c.settlementId);if(s)c.center={x:s.x,y:s.y};});const active=state.duchies.length;state.kingdoms.forEach(k=>{const cs=state.counties.filter(c=>c.kingdomId===k.id);if(cs.length>=2&&active===0)state.duchies.push(makeDuchy(cs));});}

  function maintainRoads(){for(let i=0;i<state.settlements.length;i++)for(let j=i+1;j<state.settlements.length;j++){const a=state.settlements[i],b=state.settlements[j];if(a.kingdomId!==b.kingdomId)continue;const exists=state.roads.some(r=>(r.from===a.id&&r.to===b.id)||(r.from===b.id&&r.to===a.id));if(!exists&&dist(a,b)<520)makeRoad(a,b);}
    state.roads.forEach(r=>{r.condition=clamp(r.condition-.003*state.speed,5,100);const roadNeedsRepair=r.condition<35;if(roadNeedsRepair){const s=state.settlements.find(x=>x.id===r.from);if(s&&s.resources.gold>1){s.resources.gold-=.15*state.speed;r.condition=clamp(r.condition+1.5,5,100);}}if(!state.caravans.some(c=>c.roadId===r.id)&&r.condition>20)makeCaravan(r);});
  }
  function updateCaravans(){state.caravans.forEach(c=>{const r=state.roads.find(x=>x.id===c.roadId);const a=state.settlements.find(s=>s.id===c.from),b=state.settlements.find(s=>s.id===c.to);if(!r||!a||!b)return;c.progress+=c.speed*state.speed*(r.condition/100);const t=c.progress<=1?c.progress:2-c.progress;c.x=a.x+(b.x-a.x)*t;c.y=a.y+(b.y-a.y)*t;if(c.progress>=2){c.progress=0;const traded=Math.min(a.resources.food,4);a.resources.food-=traded;b.resources.food+=traded;const iron=Math.min(a.resources.iron,1);a.resources.iron-=iron;b.resources.iron+=iron;const gold=(traded+iron)*.8;b.resources.gold+=gold;c.profit+=gold;r.condition=clamp(r.condition-1,5,100);}}
  }
  function supplyArmies(){state.armies.forEach(a=>{if(!a.active)return;const k=state.kingdoms.find(k=>k.id===a.kingdomId);if(!k)return;const capital=state.settlements.find(s=>s.id===k.capitalId);if(!capital)return;a.supply=clamp(a.supply-.15*state.speed,0,100);if(a.supply<25){const road=state.roads.find(r=>r.from===capital.id||r.to===capital.id);if(road)a.supply=clamp(a.supply+1.5*state.speed,0,100);}a.morale=clamp(a.morale+(a.supply>50?.02:-.05)*state.speed,0,100);if(a.supply<5)a.soldiers=Math.max(0,a.soldiers-.05*state.speed);});}

  function npcAI(n){if(!n.alive)return;n.hunger=clamp(n.hunger+.025*state.speed,0,100);n.energy=clamp(n.energy-(n.goal==='Sleep'?.01:.03)*state.speed,0,100);if(n.hunger>80){n.goal='Find food';}else if(n.roleId==='thief'&&Math.random()<.01*state.speed)n.goal='Scout for a target';else if(['king','duke','count'].includes(n.roleId))n.goal='Govern territory';else if(['trader','merchant'].includes(n.roleId))n.goal='Trade goods';else if(['wizard','mage'].includes(n.roleId))n.goal='Research magic';else if(['soldier','knight','captain','general'].includes(n.roleId)&&state.war)n.goal='March with army';else if(n.hour<6)n.goal='Sleep';else n.goal=n.roleId==='farmer'?'Farm':n.roleId==='blacksmith'?'Work at smithy':'Work';if(!n.target||Math.random()<.02*state.speed){const s=settlement(n);if(s){n.target={x:s.x+Math.random()*100-50,y:s.y+Math.random()*100-50};}}if(n.target){const d=dist(n,n.target);if(d>4){n.x+=(n.target.x-n.x)/d*n.speed*state.speed;n.y+=(n.target.y-n.y)/d*n.speed*state.speed;}}if(Math.random()<.003*state.speed&&n.age>20&&n.age<45)birth(n);if(n.age>88&&Math.random()<.001*state.speed)die(n,'old age');}
  function birth(parent){const mates=alive().filter(x=>x.settlementId===parent.settlementId&&x.sex!==parent.sex&&x.age>=20&&x.age<=42&&x.id!==parent.id);const mate=mates[0];if(!mate)return;const kid=createNpc(state.npcs.length,faction(parent).id,settlement(parent));kid.age=0;kid.sex=Math.random()>.5?'F':'M';kid.parentIds=[parent.id,mate.id];kid.trait=Math.random()<.5?parent.trait:mate.trait;kid.settlementId=parent.settlementId;kid.home=parent.home;kid.x=parent.x;kid.y=parent.y;kid.roleId='child';kid.roleName='Child';kid.wealth=0;parent.childrenIds.push(kid.id);mate.childrenIds.push(kid.id);state.npcs.push(kid);if(!parent.familyId){const f=createFamily(parent.name);createClan(f);parent.familyId=f.id;}kid.familyId=parent.familyId;family(parent).members.push(kid.id);memory(parent,`A child named ${kid.name} was born.`);memory(mate,`A child named ${kid.name} was born.`);}
  function inherit(dead){const f=family(dead);if(!f)return;f.deadMembers++;const candidates=alive().filter(n=>n.familyId===f.id&&n.id!==dead.id);const direct=candidates.find(n=>dead.childrenIds?.includes(n.id))||candidates.sort((a,b)=>b.age-a.age)[0];if(direct){direct.wealth+=(dead.wealth||0)*.8;f.wealth+=((dead.wealth||0)*.2);if(['king','duke','count','baron','mayor'].includes(dead.roleId)){direct.roleId=dead.roleId;direct.roleName=ROLES[direct.roleId]?.[0]||direct.roleId;memory(direct,`Inherited the title of ${direct.roleName} from ${dead.name}.`);log(`${direct.name} inherited ${direct.roleName} from ${dead.name}.`);}}}
  function die(n,why){if(!n.alive)return;n.alive=false;inherit(n);if(state.selected===n.id)state.selected=null;log(`${n.name} died at age ${Math.floor(n.age)} (${why}).`);}

  function simulate(){if(!state.running)return;const steps=Math.max(1,Math.round(state.speed/2));for(let i=0;i<steps;i++){state.tick++;state.hour+=.12;if(state.hour>=24){state.hour-=24;state.day++;if(state.day>30){state.day=1;state.year++;state.season=['Spring','Summer','Autumn','Winter'][(state.year-1)%4];log(`Year ${state.year} begins in ${state.season}.`);}}state.npcs.forEach(n=>{n.hour=state.hour;npcAI(n);});foundVillage();assignRoles();state.settlements.forEach(produce);hierarchy();maintainRoads();updateCaravans();supplyArmies();state.food=clamp(state.settlements.reduce((a,s)=>a+s.resources.food,0)/Math.max(1,state.settlements.length),0,100);if(state.food<20)state.stability=clamp(state.stability-.05,0,100);else state.stability=clamp(state.stability+.01,0,100);if(state.war&&Math.random()<.004*state.speed)log('Scouts report fighting along the frontier.');if(state.plague&&Math.random()<.002*state.speed){const victim=pick(alive());if(victim)victim.health-=15;}}render();}

  function terrain(x,y){const river=Math.abs(y-(Math.sin(x/180)*100+80))<32;const mountain=(Math.sin(x/210)+Math.cos(y/170))>1.15;const forest=(Math.sin(x/70)*Math.cos(y/80))>.35;return {river,mountain,forest};}
  function screenToWorld(px,py){return{x:(px-canvas.clientWidth/2)/state.camera.zoom+state.camera.x,y:(py-canvas.clientHeight/2)/state.camera.zoom+state.camera.y};}
  function worldToScreen(x,y){return{x:(x-state.camera.x)*state.camera.zoom+canvas.clientWidth/2,y:(y-state.camera.y)*state.camera.zoom+canvas.clientHeight/2};}
  function drawTerrain(){const w=canvas.clientWidth,h=canvas.clientHeight;ctx.fillStyle='#10251e';ctx.fillRect(0,0,w,h);ctx.save();ctx.translate(w/2-state.camera.x*state.camera.zoom,h/2-state.camera.y*state.camera.zoom);ctx.scale(state.camera.zoom,state.camera.zoom);ctx.fillStyle='#16372a';ctx.fillRect(-W/2,-H/2,W,H);for(let x=-W/2;x<W/2;x+=80)for(let y=-H/2;y<H/2;y+=80){const t=terrain(x,y);if(t.mountain)ctx.fillStyle='#34453f';else if(t.forest)ctx.fillStyle='#1d4a31';else ctx.fillStyle='#204532';ctx.fillRect(x,y,82,82);}ctx.fillStyle='#235e78';ctx.beginPath();ctx.moveTo(-W/2,Math.sin(-W/2/180)*100+80);for(let x=-W/2;x<=W/2;x+=15)ctx.lineTo(x,Math.sin(x/180)*100+80);ctx.lineTo(W/2,H/2);ctx.lineTo(-W/2,H/2);ctx.closePath();ctx.globalAlpha=.75;ctx.fill();ctx.globalAlpha=1;if(state.showGrid){ctx.strokeStyle='rgba(255,255,255,.05)';ctx.lineWidth=1/state.camera.zoom;for(let x=-W/2;x<=W/2;x+=50){ctx.beginPath();ctx.moveTo(x,-H/2);ctx.lineTo(x,H/2);ctx.stroke();}for(let y=-H/2;y<=H/2;y+=50){ctx.beginPath();ctx.moveTo(-W/2,y);ctx.lineTo(W/2,y);ctx.stroke();}}
    state.roads.forEach(r=>{const a=state.settlements.find(s=>s.id===r.from),b=state.settlements.find(s=>s.id===r.to);if(!a||!b)return;ctx.strokeStyle=r.condition>60?'#8d7553':r.condition>30?'#6b624d':'#493f35';ctx.lineWidth=Math.max(2,5/state.camera.zoom);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.quadraticCurveTo((a.x+b.x)/2,(a.y+b.y)/2-40,b.x,b.y);ctx.stroke();});
    state.duchies.forEach(d=>{d.countyIds.forEach(cid=>{const c=state.counties.find(x=>x.id===cid);if(!c)return;ctx.strokeStyle='rgba(245,209,123,.24)';ctx.lineWidth=3/state.camera.zoom;ctx.beginPath();ctx.arc(c.center.x,c.center.y,d.radius,0,Math.PI*2);ctx.stroke();});});
    state.kingdoms.forEach(k=>{const own=state.settlements.filter(s=>s.kingdomId===k.id);if(!own.length)return;ctx.strokeStyle=k.color;ctx.globalAlpha=.3;ctx.lineWidth=6/state.camera.zoom;own.forEach(s=>{ctx.beginPath();ctx.arc(s.x,s.y,s.radius+35,0,Math.PI*2);ctx.stroke();});ctx.globalAlpha=1;});
    state.settlements.forEach(s=>{ctx.fillStyle=s.type==='kingdom'?'#f5d17b':s.type==='city'?'#d7a7ff':'#8fd694';ctx.beginPath();ctx.arc(s.x,s.y,s.type==='kingdom'?18:s.type==='city'?13:9,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff';ctx.globalAlpha=.22;ctx.beginPath();ctx.arc(s.x,s.y,s.radius,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1;ctx.fillStyle='#e7efe9';ctx.font='bold 12px Segoe UI';ctx.fillText(s.name,s.x+12,s.y-12);});
    state.armies.forEach(a=>{if(!a.active)return;ctx.fillStyle='#ef7272';ctx.beginPath();ctx.arc(a.x,a.y,7,0,Math.PI*2);ctx.fill();});
    state.caravans.forEach(c=>{ctx.fillStyle='#e8bc5b';ctx.beginPath();ctx.arc(c.x,c.y,4,0,Math.PI*2);ctx.fill();});
    alive().forEach(n=>{ctx.fillStyle=n.color;ctx.beginPath();ctx.arc(n.x,n.y,5,0,Math.PI*2);ctx.fill();if(n.id===state.selected){ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.beginPath();ctx.arc(n.x,n.y,10,0,Math.PI*2);ctx.stroke();}if(state.showNames&&state.camera.zoom>.75){ctx.fillStyle='rgba(255,255,255,.8)';ctx.font='9px Segoe UI';ctx.fillText(n.name,n.x+7,n.y+3);}});ctx.restore();}

  function renderPanels(){const a=alive();el.year.textContent=state.year;el.season.textContent=state.season;el.population.textContent=a.length;el.families.textContent=new Set(a.map(n=>n.familyId).filter(Boolean)).size;el.settlements.textContent=state.settlements.length;el.food.textContent=`${Math.round(state.food)}%`;el.stability.textContent=`${Math.round(state.stability)}%`;el.worldStatus.textContent=state.war?'War':'Peaceful';el.tickLabel.textContent=`tick ${state.tick}`;el.speedLabel.textContent=`${state.speed}×`;
    const stats=[['Kingdoms',state.kingdoms.length],['Counties',state.counties.length],['Duchies',state.duchies.length],['Roads',state.roads.length],['Caravans',state.caravans.length],['Armies',state.armies.filter(a=>a.active).length]];el.worldStats.innerHTML=stats.map(x=>`<div class="metric"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');el.factionList.innerHTML=state.kingdoms.map(k=>`<div class="faction"><i style="background:${k.color}"></i><span>${k.name}</span><b>${alive().filter(n=>n.faction===k.id).length}</b></div>`).join('');
    const sel=alive().find(n=>n.id===state.selected);if(sel){const f=family(sel),k=faction(sel),s=settlement(sel);el.inspectorContent.innerHTML=`<div class="person-head"><div class="portrait" style="background:${sel.color}">${sel.name[0]}</div><div><h3>${sel.name}</h3><span>Age ${Math.floor(sel.age)} · ${sel.roleName}</span></div></div><div class="goal"><b>Goal:</b> ${sel.goal}</div><div class="bio-grid"><span>Trait<b>${sel.trait}</b></span><span>Wealth<b>${Math.floor(sel.wealth)} gold</b></span><span>Family<b>${f?.name||'None'}</b></span><span>Clan<b>${f?state.clans.find(c=>c.id===f.clanId)?.name||'None':'None'}</b></span><span>Settlement<b>${s?.name||'Nomad'}</b></span><span>Realm<b>${k?.name||'None'}</b></span></div><h4>Memories</h4><div class="memories">${sel.memories.map(m=>`<div>Y${m.year} · ${m.text}</div>`).join('')||'<div>No major memories yet.</div>'}</div>`;el.selectedNeedMood.textContent=`Mood ${Math.round(sel.mood)}`;const needs=[['Hunger',100-sel.hunger],['Energy',sel.energy],['Health',sel.health],['Mood',sel.mood]];el.needsChart.innerHTML=needs.map(([n,v])=>`<div class="need"><div><span>${n}</span><b>${Math.round(v)}%</b></div><div class="bar"><i style="width:${clamp(v,0,100)}%"></i></div></div>`).join('');}else{el.inspectorContent.innerHTML='<div class="empty-state">Select an NPC to inspect their life, family, clan, role, territory and inheritance.</div>';el.selectedNeedMood.textContent='No selection';el.needsChart.innerHTML='';}}
  function render(){resize();drawTerrain();renderPanels();}
  function resize(){const r=canvas.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);}
  function clickNpc(e){const p=screenToWorld(e.offsetX,e.offsetY);let best=null,bd=16/state.camera.zoom;alive().forEach(n=>{const d=dist(n,p);if(d<bd){best=n;bd=d;}});if(best){state.selected=best.id;render();}}
  function controls(){el.toggleSim.onclick=()=>{state.running=!state.running;el.toggleSim.textContent=state.running?'⏸ Pause':'▶ Resume';};el.speed.oninput=()=>state.speed=+el.speed.value;document.getElementById('toggleNames').onclick=()=>{state.showNames=!state.showNames;render();};document.getElementById('toggleGrid').onclick=()=>{state.showGrid=!state.showGrid;render();};document.getElementById('toggleTrails').onclick=()=>{state.showTrails=!state.showTrails;render();};document.getElementById('closeInspector').onclick=()=>{state.selected=null;render();};document.querySelectorAll('[data-event]').forEach(b=>b.onclick=()=>eventAction(b.dataset.event));document.getElementById('foundFaction').onclick=()=>{const k=createKingdom(pick(['Aurelia','Ironvale','Moonmere','Oakshield','Raven Coast']));const base=state.settlements[0];const s=createSettlement(`${k.name} Hold`,base.x+500,base.y+250,'village',k.id,null);makeCounty(s);log(`A new faction, ${k.name}, establishes ${s.name}.`);render();};canvas.addEventListener('click',clickNpc);canvas.addEventListener('wheel',e=>{e.preventDefault();state.camera.zoom=clamp(state.camera.zoom*(e.deltaY<0?1.1:.9),.45,3);render();},{passive:false});canvas.addEventListener('mousedown',e=>{state.dragging=true;state.dragStart={x:e.clientX,y:e.clientY,cx:state.camera.x,cy:state.camera.y};});window.addEventListener('mouseup',()=>state.dragging=false);window.addEventListener('mousemove',e=>{if(!state.dragging)return;state.camera.x=state.dragStart.cx-(e.clientX-state.dragStart.x)/state.camera.zoom;state.camera.y=state.dragStart.cy-(e.clientY-state.dragStart.y)/state.camera.zoom;render();});}
  function eventAction(name){if(name==='reset')return reset();if(name==='festival'){alive().forEach(n=>n.mood=clamp(n.mood+12,0,100));state.stability=clamp(state.stability+7,0,100);log('A grand festival brings the settlements together.');}if(name==='storm'){state.weather='Storm';state.food=Math.max(0,state.food-8);log('A major storm damages farms and roads.');}if(name==='plague'){state.plague=!state.plague;log(state.plague?'A plague is spreading through the realm.':'Healers have contained the plague.');}if(name==='war'){state.war=!state.war;log(state.war?'Kingdoms mobilize for war along the frontier.':'A tense peace returns to the frontier.');if(state.war)state.kingdoms.forEach(k=>{const cap=state.settlements.find(s=>s.id===k.capitalId);if(cap)state.armies.push(makeArmy(k.id,cap.x,cap.y));state.armies[state.armies.length-1].active=true;});}if(name==='meteor'){log('A meteor crashes into the wilderness.');state.stability=clamp(state.stability-8,0,100);}render();}

  function init(){controls();reset();setInterval(simulate,700);}
  init();
})();
