function eventAction(name){if(name==='reset')return reset();if(name==='festival'){alive().forEach(n=>n.mood=clamp(n.mood+12,0,100));state.stability=clamp(state.stability+7,0,100);alive().filter(n=>n.settlementId).forEach(n=>n.reputation=clamp(n.reputation+1,0,100));log('A grand festival improves morale and public reputation.')}if(name==='storm'){state.weather='Storm';state.food=Math.max(0,state.food-8);state.roads.forEach(r=>r.condition=Math.max(5,r.condition-8));alive().forEach(n=>n.grievance=clamp(n.grievance+1,0,100));log('A major storm damages farms and roads.')}if(name==='plague'){state.plague=!state.plague;log(state.plague?'A plague is spreading through the realm.':'Healers have contained the plague.')}if(name==='war'){state.war=!state.war;log(state.war?'Kingdoms mobilize for war along the frontier.':'A tense peace returns to the frontier.');if(state.war)state.kingdoms.forEach(k=>{const cap=state.settlements.find(s=>s.id===k.capitalId);if(cap){const a=makeArmy(k.id,cap.x,cap.y);a.active=true;state.armies.push(a)}})}if(name==='meteor'){state.stability=clamp(state.stability-8,0,100);alive().forEach(n=>n.fortune=clamp(n.fortune-1,0,100));log('A meteor crashes into the wilderness.')}renderNow()}
function registerSystem(system){const entry=typeof system==='function'?{name:system.name||'anonymous',step:system,priority:100}:system;if(!entry||typeof entry.step!=='function')return()=>{};const existing=state.systems.find(s=>s.step===entry.step||s===entry);if(!existing){state.systems.push(entry);state.systems.sort((a,b)=>(a.priority??100)-(b.priority??100));}return()=>{const i=state.systems.indexOf(existing||entry);if(i>=0)state.systems.splice(i,1)}}
state.registerSystem=registerSystem;
function simulate(){if(!state.running)return;for(let i=0;i<Math.max(1,Math.round(state.speed/2));i++){state.tick++;state.hour+=.12;if(state.hour>=24){state.hour-=24;state.day++;if(state.day>30){state.day=1;state.year++;state.season=['Spring','Summer','Autumn','Winter'][(state.year-1)%4];log(`Year ${state.year} begins in ${state.season}.`)}}state.npcs.forEach(n=>{n.hour=state.hour;npcAI(n)});state.settlements.forEach(produce);hierarchy();maintainRoads();recomputeTerritory();updateCaravans();moveArmies();supplyArmies();state.food=clamp(state.settlements.reduce((a,s)=>a+s.resources.food,0)/Math.max(1,state.settlements.length),0,100);state.stability=clamp(state.stability+(state.food<20?-.05:.01),0,100);state.systems.slice().forEach(system=>{try{const step=typeof system==='function'?system:system?.step;if(typeof step==='function')step(state)}catch(error){const name=typeof system==='function'?(system.name||'anonymous'):(system?.name||'unnamed');console.error(`Simulation system error [${name}]`,error?.stack||error)}});if(state.war&&Math.random()<.004*state.speed)log('Scouts report fighting along the frontier.');if(state.plague&&Math.random()<.002*state.speed){const v=pick(alive());if(v)v.health-=15}}renderNow()}
window.SIM_STATE=state;
window.SIM_RENDER=render;
window.SIM_API={state,registerSystem,log,micro,alive,createNpc,createSettlement,createKingdom,worldToTile:wn,tileToWorld:nw,tileId:territoryClaimCell,recomputeTerritory,claimTerritoryAt,revokeTerritoryAt,isKingdomAtWar:kingdomAtWar,forceBorderWar};
function init(){controls();reset();setInterval(simulate,700)}init();
})();
