(() => {
  const state=window.SIM_STATE;if(!state)return;
  const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const arr=v=>Array.isArray(v)?v:[];
  const el=(tag,attrs={},html='')=>{const e=document.createElement(tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));e.innerHTML=html;return e;};
  const history=()=>{
    const out=[];
    (state.settlements||[]).forEach(s=>arr(s.history).forEach(text=>out.push({year:Number((String(text).match(/Year\s+(\d+)/i)||[])[1]||state.year),type:'Settlement',title:s.name,text,ref:s.id,icon:'🏘️'})));
    (state.kingdoms||[]).forEach(k=>{arr(k.history).forEach(text=>out.push({year:Number((String(text).match(/Year\s+(\d+)/i)||[])[1]||state.year),type:'Kingdom',title:k.name,text,ref:k.id,icon:'👑'}));arr(k.strategy?.history).forEach(x=>{const text=typeof x==='string'?x:(x.text||x.event||'Strategic development');out.push({year:Number(x?.year||state.year),type:'Strategy',title:k.name,text,ref:k.id,icon:'♟️'});});});
    (state.internationalHistory?.events||[]).forEach(x=>out.push({year:Number(x.year||state.year),type:'International',title:x.title||'International event',text:x.text||x.description||'A major international shift occurred.',ref:x.id||null,icon:'🌍'}));
    (state.regionalHistory?.events||[]).forEach(x=>out.push({year:Number(x.year||state.year),type:'Regional',title:x.regionName||x.title||'Regional event',text:x.text||x.description||x.event||'A regional event reshaped the world.',ref:x.id||null,icon:'📜'}));
    return out.sort((a,b)=>b.year-a.year).slice(0,250);
  };
  function mount(){
    if(document.getElementById('chronicleModal'))return;
    const style=el('style',{},`#chronicleModal{position:fixed;inset:0;background:rgba(2,7,6,.72);z-index:2000;display:none;align-items:center;justify-content:center;padding:22px}.chronicle-shell{width:min(980px,96vw);height:min(760px,90vh);display:flex;flex-direction:column;background:#0b1513;border:1px solid rgba(180,215,202,.18);border-radius:16px;box-shadow:0 28px 90px rgba(0,0,0,.55);overflow:hidden;color:#e8f3ee;font:13px Segoe UI,sans-serif}.chronicle-head{display:flex;justify-content:space-between;align-items:center;padding:16px 18px;border-bottom:1px solid rgba(255,255,255,.07)}.chronicle-head h2{margin:0;font-size:18px}.chronicle-head small{color:#80968e}.chronicle-actions{display:flex;gap:7px;align-items:center}.chronicle-actions button{border:1px solid rgba(255,255,255,.1);background:#13221f;color:#dcebe6;border-radius:8px;padding:7px 10px;cursor:pointer}.chronicle-body{display:grid;grid-template-columns:190px 1fr;min-height:0;flex:1}.chronicle-side{padding:12px;border-right:1px solid rgba(255,255,255,.07);overflow:auto}.chronicle-filter{display:block;width:100%;text-align:left;margin:5px 0;padding:8px 9px;border-radius:8px;border:1px solid transparent;background:transparent;color:#a8beb6;cursor:pointer}.chronicle-filter.active{background:#183029;color:#f0f8f5;border-color:rgba(180,215,202,.16)}.chronicle-content{overflow:auto;padding:16px 18px}.chronicle-era{margin:3px 0 13px;color:#8ea59d;font-size:11px;letter-spacing:1.1px;text-transform:uppercase}.chronicle-item{position:relative;padding:0 0 16px 28px;border-left:1px solid rgba(165,198,186,.18);margin-left:7px}.chronicle-item:before{content:'';position:absolute;left:-5px;top:2px;width:9px;height:9px;border-radius:50%;background:#8fb8a9;box-shadow:0 0 0 3px #0b1513}.chronicle-card{background:#101e1b;border:1px solid rgba(255,255,255,.07);border-radius:10px;padding:11px 12px}.chronicle-meta{display:flex;gap:8px;align-items:center;color:#759087;font-size:11px;margin-bottom:5px}.chronicle-title{font-weight:700;color:#edf5f2}.chronicle-text{color:#b4c5bf;line-height:1.45;margin-top:4px}.chronicle-empty{padding:40px 20px;color:#81958d;text-align:center}.chronicle-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;padding:12px 18px;border-bottom:1px solid rgba(255,255,255,.06)}.chronicle-stat{background:#101e1b;border-radius:9px;padding:8px 10px}.chronicle-stat span{display:block;color:#789087;font-size:10px}.chronicle-stat strong{display:block;margin-top:3px;font-size:15px}@media(max-width:700px){.chronicle-body{grid-template-columns:1fr}.chronicle-side{display:flex;gap:4px;overflow:auto;border-right:0;border-bottom:1px solid rgba(255,255,255,.07)}.chronicle-filter{white-space:nowrap}.chronicle-stats{grid-template-columns:repeat(2,1fr)}}`);
    document.head.appendChild(style);
    const modal=el('div',{id:'chronicleModal'});modal.innerHTML=`<div class="chronicle-shell"><div class="chronicle-head"><div><h2>📖 World Chronicle</h2><small>Everything Everglen remembers</small></div><div class="chronicle-actions"><select id="chronicleYear" style="background:#13221f;color:#dcebe6;border:1px solid rgba(255,255,255,.1);border-radius:8px;padding:7px"></select><button id="chronicleClose">× Close</button></div></div><div id="chronicleStats" class="chronicle-stats"></div><div class="chronicle-body"><aside id="chronicleFilters" class="chronicle-side"></aside><section id="chronicleContent" class="chronicle-content"></section></div></div>`;
    document.body.appendChild(modal);
    document.getElementById('chronicleClose').onclick=()=>modal.style.display='none';
    modal.addEventListener('click',e=>{if(e.target===modal)modal.style.display='none'});
    const side=document.getElementById('chronicleFilters');const filters=['All','Kingdom','Settlement','Regional','Strategy','International'];let active='All';
    filters.forEach(f=>{const b=el('button',{class:'chronicle-filter'+(f==='All'?' active':'')},f);b.onclick=()=>{active=f;side.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(active)};side.appendChild(b)});
    document.getElementById('chronicleYear').onchange=()=>render(active);
    function render(filter){
      const items=history().filter(x=>filter==='All'||x.type===filter);const years=[...new Set(items.map(x=>x.year))].sort((a,b)=>b-a);const yearSel=document.getElementById('chronicleYear');const current=yearSel.value;if(!yearSel.options.length){yearSel.appendChild(el('option',{value:'all'},'All years'));years.forEach(y=>yearSel.appendChild(el('option',{value:String(y)},`Year ${y}`)));}else{const known=new Set([...yearSel.options].map(o=>o.value));years.forEach(y=>{if(!known.has(String(y)))yearSel.appendChild(el('option',{value:String(y)},`Year ${y}`));});}yearSel.value=current||'all';const yr=yearSel.value==='all'?null:Number(yearSel.value);const shown=yr?items.filter(x=>x.year===yr):items;
      const events=shown.length;const settlements=new Set(shown.filter(x=>x.type==='Settlement').map(x=>x.ref)).size;const kingdoms=new Set(shown.filter(x=>x.type==='Kingdom'||x.type==='Strategy').map(x=>x.ref)).size;const international=shown.filter(x=>x.type==='International').length;document.getElementById('chronicleStats').innerHTML=`<div class="chronicle-stat"><span>Events</span><strong>${events}</strong></div><div class="chronicle-stat"><span>Settlements</span><strong>${settlements}</strong></div><div class="chronicle-stat"><span>Kingdoms</span><strong>${kingdoms}</strong></div><div class="chronicle-stat"><span>World shifts</span><strong>${international}</strong></div>`;
      const c=document.getElementById('chronicleContent');if(!shown.length){c.innerHTML='<div class="chronicle-empty">No recorded events in this view yet.</div>';return;}let lastYear=null;c.innerHTML=shown.map(x=>{const era=lastYear!==x.year?`<div class="chronicle-era">Year ${x.year}</div>`:'';lastYear=x.year;return `${era}<article class="chronicle-item"><div class="chronicle-card"><div class="chronicle-meta"><span>${x.icon}</span><span>${esc(x.type)}</span></div><div class="chronicle-title">${esc(x.title)}</div><div class="chronicle-text">${esc(x.text)}</div></div></article>`}).join('');
    }
    window.EVERGLEN_CHRONICLE={open:()=>{modal.style.display='flex';render(active);},refresh:()=>render(active)};
    const btn=el('button',{id:'openChronicle'},'📖 Chronicle');const controls=document.querySelector('.controls');if(controls)controls.insertBefore(btn,controls.querySelector('.danger')||null);btn.onclick=window.EVERGLEN_CHRONICLE.open;
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();